 'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const candidate=path.resolve(__dirname,'../../模板.html'),project=process.env.OVERVIEW_PROJECT_PATH||(fs.existsSync(candidate)?path.dirname(candidate):process.cwd());
const preview=path.join(__dirname,'template-overview-settings-preview.html'),html=fs.readFileSync(process.env.OVERVIEW_TEMPLATE||(fs.existsSync(preview)?preview:path.join(project,'模板.html')),'utf8');
const block=html.slice(html.indexOf('const FIXED_OVERVIEW_MODULES='),html.indexOf('function curUiStyle()',html.indexOf('const FIXED_OVERVIEW_MODULES=')));
const range=(a,b)=>{const begin=html.indexOf(a),end=html.indexOf(b,begin);assert.ok(begin>=0&&end>begin,a);return html.slice(begin,end);};
const moduleSource=range('async function showModule()', '/* 模块读取入口 showModule 结束 */');
const openSource=range('function openItem(path, quiet)', 'function vOpen(path)');
const readingSource=range('/* ================= 通用读取事务 Common route reading ================= */','/* ================= 通用读取事务 Common route reading 结束 ================= */');
const autoSource=readingSource+range('async function showAuto()', 'function asec(');
const autoTocSource=range('function renderAutoToc()', "$('#toc').addEventListener('keydown'");
const commonSource=range('const COMMON_OVERVIEW_VIEWS=', 'function setToc(');
const modules=()=>['想法','蓝图','戒律','源代码','测试','写论文','剪辑','写小说'].map(name=>({name,en:''}));
class Element{
 constructor(name='div'){this.id='';this.name=name;this.tagName=name.toUpperCase();this.dataset={};this.attributes={};this.children=[];this.listeners={};this.innerHTML='';this.textContent='';this.isConnected=true;this.checked=false;this.disabled=false;this.value='';this.open=false;const classes=new Set();this.classList={add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle:(x,on)=>on?classes.add(x):classes.delete(x)};}
 addEventListener(type,fn){(this.listeners[type]??=[]).push(fn);}setAttribute(k,v){this.attributes[k]=v;if(k==='id')this.id=String(v);}hasAttribute(k){return Object.hasOwn(this.attributes,k)||k==='data-overview-others'&&Object.hasOwn(this.dataset,'overviewOthers');}
 appendChild(x){x.parentNode=this;x.parent=this;this.children.push(x);return x;}prepend(x){x.parentNode=this;x.parent=this;this.children.unshift(x);}remove(){if(this.parent)this.parent.children=this.parent.children.filter(c=>c!==this);this.parentNode=null;this.parent=null;this.isConnected=false;}
 querySelector(selector){if(selector==='[data-common-overview]')return this.children.find(x=>x.dataset.commonOverview)||null;return null;}querySelectorAll(selector){return selector==='.row'?this.children:[];}
 closest(selector){const names={'[data-overview-enabled]':'overviewEnabled','[data-module-overview]':'moduleOverview','[data-overview-layout]':'overviewLayout','[data-overview-choice]':'overviewChoice'};return names[selector]&&Object.hasOwn(this.dataset,names[selector])?this:null;}
}
function fixture(initial={}){
 const storage=new Map(Object.entries(initial)),writes=[],events=[],windowListeners={},controls=[],nodes=new Map(['#setview','#toc','#modview','#tree','#autoview','.shell'].map(k=>[k,new Element()]));
 for(const [key,node] of nodes)if(key[0]==='#')node.id=key.slice(1);
 const calls={maps:0,files:[],intro:0,dashboard:0,board:0,toc:0,dispose:0,requests:[],close:0};
 const c={console,Map,Set,URL,encodeURIComponent,decodeURIComponent,S:{project:{root:'C:/TEMP/甲',name:'样板'},modules:modules()},view:'settings',cur:'戒律',online:true,
  NAV_SPECS:[['notesTab','books','笔记本','Notebook'],['inboxTab','inbox','入口','Intake'],['searchTab','search','搜索','Search'],['savesTab','archive','存档','Archives'],['qaTab','question','问答','Q&A'],['plansTab','scroll','计划','Plans'],['autoTab','flow','自动化','Automation'],['skillsTab','magic','技能','Skills'],['toolsTab','hammer','工具','Tools'],['cmdsTab','bolt','指令','Commands'],['setTab','sliders','设置','Settings'],['guideTab','book','使用说明','Guide'],['trashTab','trash','清理','Cleanup']],
  MODULEMAP:'#模块总览',BLUEPRINTMAP:'#蓝图总览',RULEMAP:'#戒律总览',CODEMAP:'#代码地图',CODELIST:'#代码清单',WORKBENCH:'#编程工作台',PANORAMA:'#项目全景',READ:'#阅读:',REQ:'#需求:',IDEA:'#想法:',DL:'#下载:',LIB:'#文献:',PAPER:'#论文:',
  localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{storage.set(k,v);writes.push({k,v});}},CustomEvent:class{constructor(type,opts){this.type=type;this.detail=opts.detail;}},
  document:{title:'',fullscreenElement:null,body:new Element('body'),createElement:name=>new Element(name),getElementById:()=>new Element(),querySelector:s=>nodes.get(s),querySelectorAll:s=>controls.filter(x=>s==='[data-overview-enabled]'?Object.hasOwn(x.dataset,'overviewEnabled'):s==='[data-module-overview]'?Object.hasOwn(x.dataset,'moduleOverview'):false)},
  window:{addEventListener:(type,fn)=>{(windowListeners[type]??=[]).push(fn);},dispatchEvent:e=>{events.push(e);for(const fn of windowListeners[e.type]||[])fn(e);},scrollTo(){}},MutationObserver:class{observe(){}},esc:s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])),$:s=>nodes.get(s),
  MV:{name:'戒律',sel:null,tree:{items:[{path:'资料/戒律/真实.md',name:'真实.md'}]},shown:null},CMAPCTL:null,GOVMAPCTL:null,GOVMAPHOST:null,RD:{hid:false},ZEN:{slide:null},MODULE_READ:{serial:0},location:{hash:'#/auto'},history:{replaceState(_a,_b,url){c.location.hash=url;}},
  moduleDefaultFile:()=>c.MV.tree?.items.find(n=>!n.virtual&&!n.dir&&n.path&&n.path[0]!=='#')?.path||null,moduleOverviewPath:name=>name==='蓝图'?'#蓝图总览':name==='戒律'?'#戒律总览':name==='源代码'?'#代码地图':'#模块总览',
  invalidateModuleReading:()=>c.MODULE_READ.serial++,moduleReadBegin:path=>({path,root:c.S.project.root,host:nodes.get('#modview'),treeHost:nodes.get('#tree')}),moduleReadFailure(){},moduleReadResult:(tx,scope,ok)=>({tx,scope,ok}),moduleReadCurrent:()=>true,moduleReadDrop(){},moduleReadComplete:async()=>true,moduleReadRoot:()=>c.S.project.root,zenOn:()=>false,zenLand(){},zenPos(){},zenPrefetch(){},renderTree:()=>calls.toc++,renderIntro:()=>calls.intro++,
  showModuleOverview:()=>calls.maps++,showPanorama:()=>calls.maps++,showRuleMap:()=>calls.maps++,showCodemap:()=>calls.maps++,showFile:(p)=>{calls.files.push(p);c.MV.sel=p;},showReader(){},rdReturnFloating(){},stickyNoteIcon(){return '';},showNeeds(){},showIdea(){},showDownloads(){},showLibrary(){},showPaper(){},
  AUSEL:'s:home',AUSERIAL:0,AUWAIT:false,ADERR:[],ADUPDATED:'',WD:null,GD:null,AT:[],AJ:[],ATools:[],AG:{items:[]},WL:{items:[]},AB:{items:[]},AU:{runs:[],workflows:[],handovers:[]},ADL:{},
  readingFlames:zh=>zh,completeReading:async()=>{},failReading:(host,zh)=>{host.innerHTML=zh;},
  AutoDashboard:{dispose:()=>calls.dispose++},mountAutoDashboard:()=>calls.dashboard++,renderAutoToc:()=>calls.toc++,boardHtml:()=>{calls.board++;return'ACTUAL_BOARD';},gkey:r=>'g:'+r.code,apage:()=>'',setToc(){},toast(){},autoTyping:()=>false,getLang:()=> 'zh',
  AUTOCROOT:'',AUTOCSEL:'',AUTOCOPEN:{},needItems:()=>[],saveAutoFolds(){},uiIcon:()=>'',arow:(key,label)=>'<div class="row" data-auto="'+key+'"><span class="nm">'+label+'</span></div>',aplus:()=>'',GLAMP:{},overviewNotes(){},
  api:async(method,url)=>{calls.requests.push({method,url});assert.equal(method,'GET');if(url.endsWith('/tree'))return c.MV.tree;if(url==='api/auto')return{runs:[],workflows:[],handovers:[]};if(url==='api/auto/launch')return{};return{items:[]};}
 };
 c.AgentAllocation=c.window.AgentAllocation={dispose(){calls.dispose++;}};c.WorkflowEditor=c.window.WorkflowEditor={dispose(){calls.dispose++;}};
 c.GovMap=c.window.GovMap={mount(_host,opts,helpers){calls.maps++;c.lastMapHelpers=helpers;return{update(){calls.maps++;},destroy(){calls.close++;}};}};
 vm.createContext(c);vm.runInContext(block,c);const run=s=>vm.runInContext(s,c);
 function control(key){const enabled=new Element('input'),mode=new Element('select');enabled.dataset.overviewEnabled=key;mode.dataset.moduleOverview=key;controls.push(enabled,mode);c.syncModuleOverviewControls(key);return{enabled,mode};}
 return{c,storage,writes,events,calls,nodes,controls,run,control,load:source=>vm.runInContext(source,c)};
}
const prefRoot='c:/temp/甲';
const pref=(rows,root=prefRoot)=>JSON.stringify({schema:1,projects:{[root]:rows}});
test('only source, blueprint and archives default on; automation and all other known modules default off',()=>{const f=fixture();for(const key of ['源代码','蓝图','common:saves'])assert.equal(f.c.moduleOverviewEnabled(key),true,key);for(const key of ['common:auto','戒律','想法','测试','剪辑','common:tools'])assert.equal(f.c.moduleOverviewEnabled(key),false,key);});
test('settings exposes three primary rows and puts every other allowed module inside native details',()=>{const f=fixture(),h=f.c.overviewChoices(),main=h.slice(0,h.indexOf('<details'));assert.equal((main.match(/data-overview-row=/g)||[]).length,3);assert.match(main,/源代码[\s\S]*common:auto[\s\S]*common:saves/);assert.match(h,/<details[^>]*data-overview-others>/);assert.match(h,/其他模块/);assert.doesNotMatch(h,/data-overview-choice|data-overview-layout|No overview|不使用总览/);for(const key of ['common:settings','common:guide','common:trash','common:notes','common:inbox','common:search'])assert.doesNotMatch(h,new RegExp('data-overview-row="'+key+'"'));});
test('all three protected rows have disabled checked enable controls but editable mode choices',()=>{const f=fixture();for(const key of ['源代码','蓝图','common:saves']){const h=f.c.overviewModuleRows(f.c.overviewModuleList().filter(m=>m.key===key));assert.match(h,/type="checkbox"[^>]* checked disabled/);assert.doesNotMatch(h,/<select[^>]* disabled/);assert.equal(f.c.applyModuleOverviewEnabled(key,false),false);assert.equal(f.c.applyModuleOverviewMode(key,'off'),false);assert.equal(f.c.moduleOverviewEnabled(key),true);}});
test('unknown and excluded keys are rejected for read, writes and rendering',()=>{const f=fixture();for(const key of ['bad-key','__proto__','common:undefined','common:guide','common:settings','common:notes']){const before=f.writes.length;assert.equal(f.c.researchOverviewMode(key),null);assert.equal(f.c.moduleOverviewEnabled(key),false);assert.equal(f.c.applyModuleOverviewEnabled(key,true),false);assert.equal(f.c.applyModuleOverviewMode(key,'flow'),false);assert.equal(f.writes.length,before);}assert.equal(f.c.overviewModuleRows([{key:'bad-key',name:'bad'}]),'');});
test('explicit legacy modes migrate as enabled; old off stays disabled with a recoverable map mode',()=>{const f=fixture({'tpl_overview_modules':JSON.stringify({'C:\\TEMP\\甲':{'common:auto':'flow','戒律':'model3d','剪辑':'off','common:saves':'flow','源代码':'off','蓝图':'off','bad-key':'map'}})});assert.equal(f.c.moduleOverviewEnabled('common:auto'),true);assert.equal(f.c.researchOverviewMode('common:auto'),'flow');assert.equal(f.c.researchOverviewMode('戒律'),'model3d');assert.equal(f.c.moduleOverviewEnabled('剪辑'),false);assert.equal(f.c.researchOverviewMode('剪辑'),'map');assert.equal(f.c.researchOverviewMode('common:saves'),'map');assert.equal(f.c.moduleOverviewEnabled('源代码'),true);const rows=JSON.parse(f.storage.get('tpl_overview_preferences')).projects[prefRoot];assert.equal(Object.hasOwn(rows,'bad-key'),false);});
test('restoring a forged protected off cannot switch it off or restore unknown keys',()=>{const f=fixture({'tpl_overview_preferences':pref({'源代码':{enabled:false,mode:'flow'},'蓝图':{enabled:false,mode:'model3d'},'common:saves':{enabled:false,mode:'flow'},bad:{enabled:true,mode:'map'}})});for(const key of ['源代码','蓝图','common:saves'])assert.equal(f.c.moduleOverviewEnabled(key),true);const rows=JSON.parse(f.storage.get('tpl_overview_preferences')).projects[prefRoot];assert.equal(rows['源代码'].enabled,true);assert.equal(rows['蓝图'].mode,'model3d');assert.equal(rows['common:saves'].mode,'map');assert.equal(Object.hasOwn(rows,'bad'),false);});
test('unknown schema, malformed records, mode and boolean values fail closed',()=>{for(const record of [JSON.stringify({schema:9,projects:{[prefRoot]:{'common:auto':{enabled:true,mode:'flow'}}}}),pref({'common:auto':{enabled:'true',mode:'flow'}}),pref({'common:auto':{enabled:true,mode:'bad'}}),'[1,2]','not JSON']){const f=fixture({'tpl_overview_preferences':record});assert.equal(f.c.moduleOverviewEnabled('common:auto'),false);assert.equal(f.c.moduleOverviewEnabled('源代码'),true);}});
test('enable/disable preserves the independently chosen mode and updates actual controls',()=>{const f=fixture(),ui=f.control('common:auto');assert.equal(ui.mode.disabled,true);assert.equal(f.c.applyModuleOverviewMode('common:auto','flow'),true);assert.equal(f.c.moduleOverviewEnabled('common:auto'),false);assert.equal(f.c.applyModuleOverviewEnabled('common:auto',true),true);assert.equal(ui.mode.disabled,false);assert.equal(ui.mode.value,'flow');assert.equal(f.c.applyModuleOverviewEnabled('common:auto',false),true);assert.equal(ui.mode.disabled,true);assert.equal(ui.mode.value,'flow');assert.equal(f.c.applyModuleOverviewEnabled('common:auto',true),true);assert.equal(f.c.researchOverviewMode('common:auto'),'flow');});
test('protected change handler rejects a forged checkbox off and restores its checked state',()=>{const f=fixture(),ui=f.control('源代码');ui.enabled.checked=false;f.nodes.get('#setview').listeners.change[0]({target:ui.enabled});assert.equal(ui.enabled.checked,true);assert.equal(ui.enabled.disabled,true);assert.equal(f.c.moduleOverviewEnabled('源代码'),true);});
test('saved mode and enabled state survive a fresh page while project roots remain isolated',()=>{const f=fixture();f.c.applyModuleOverviewMode('common:auto','flow');f.c.applyModuleOverviewEnabled('common:auto',true);const stored=Object.fromEntries(f.storage),other=fixture(stored);assert.equal(other.c.researchOverviewMode('common:auto'),'flow');assert.equal(other.c.moduleOverviewEnabled('common:auto'),true);other.c.S.project.root='D:/项目乙';assert.equal(other.c.moduleOverviewEnabled('common:auto'),false);other.c.applyModuleOverviewMode('common:auto','model3d');other.c.applyModuleOverviewEnabled('common:auto',true);other.c.S.project.root='C:\\TEMP\\甲';assert.equal(other.c.researchOverviewMode('common:auto'),'flow');});
test('other-modules folding is closed by default and stored only for the current project',()=>{const f=fixture(),d=new Element('details');d.dataset.overviewOthers='';d.open=true;f.nodes.get('#setview').listeners.toggle[0]({target:d});assert.equal(f.c.overviewOthersOpen(),true);f.c.S.project.root='D:/另一个';assert.equal(f.c.overviewOthersOpen(),false);assert.doesNotMatch(f.c.overviewChoices(),/data-overview-others open/);});
test('changing available module metadata does not resurrect removed or unknown keys',()=>{const f=fixture();f.c.applyModuleOverviewEnabled('剪辑',true);f.c.S.modules=f.c.S.modules.filter(m=>m.name!=='剪辑');assert.equal(f.c.moduleOverviewEnabled('剪辑'),false);f.c.S.modules.push({name:'另一个DIY'});assert.equal(f.c.moduleOverviewEnabled('另一个DIY'),false);assert.equal(f.c.applyModuleOverviewEnabled('unknown',true),false);});
test('module page resolves every disabled overview alias to its real file while preserving new read transactions',async()=>{for(const target of ['#模块总览','#戒律总览','#代码地图','#蓝图总览','#项目全景']){const f=fixture();f.c.view='mod';f.c.cur=f.c.MV.name='戒律';f.c.MV.sel=target;f.load(openSource);f.load(moduleSource);await f.c.showModule();assert.equal(f.calls.maps,0,target);assert.equal(f.calls.files.at(-1),'资料/戒律/真实.md');assert.equal(f.c.MV.sel,'资料/戒律/真实.md');assert.equal(f.calls.requests.every(r=>r.method==='GET'),true);}});
test('direct disabled map links cannot bypass the off guard and empty modules use their original intro',()=>{for(const target of ['#模块总览','#戒律总览','#代码地图','#蓝图总览','#项目全景']){const f=fixture();f.c.view='mod';f.load(openSource);f.c.openItem(target,true);assert.equal(f.calls.maps,0);assert.equal(f.calls.files.at(-1),'资料/戒律/真实.md');}const f=fixture();f.c.view='mod';f.c.MV.tree={items:[]};let closed=0;f.c.CMAPCTL={destroy:()=>closed++};f.load(openSource);f.c.openItem('#代码地图');assert.equal(f.calls.intro,1);assert.equal(closed,1);assert.equal(f.c.MV.sel,null);});
test('automation overview off routes to the board, including an invalid old selection, without any write or launch',async()=>{for(const sel of ['s:home','nonexistent']){const f=fixture();f.c.view='auto';f.c.AUSEL=sel;f.load(autoSource);await f.c.showAuto();assert.equal(f.c.AUSEL,'s:board');assert.equal(f.calls.dashboard,0);assert.equal(f.calls.board,1);assert.equal(f.calls.requests.every(r=>r.method==='GET'),true);assert.equal(f.calls.requests.some(r=>r.url.includes('/start')),false);}});
test('explicitly enabled automation retains its original dashboard',async()=>{const f=fixture();f.c.applyModuleOverviewEnabled('common:auto',true);f.c.view='auto';f.load(autoSource);await f.c.showAuto();assert.equal(f.c.AUSEL,'s:home');assert.equal(f.calls.dashboard,1);assert.equal(f.calls.board,0);assert.equal(f.calls.requests.every(r=>r.method==='GET'),true);});
test('automation directory hides only the disabled overview and keeps real task/employee/record entries',()=>{const f=fixture();f.c.view='auto';f.load(autoTocSource);f.c.renderAutoToc();let h=f.nodes.get('#toc').innerHTML;assert.doesNotMatch(h,/data-auto="s:home"/);for(const key of ['s:board','s:orders','s:agents','s:term','s:review'])assert.match(h,new RegExp('data-auto="'+key+'"'));f.c.applyModuleOverviewEnabled('common:auto',true);f.c.renderAutoToc();assert.match(f.nodes.get('#toc').innerHTML,/data-auto="s:home"/);});
test('common overview entry and direct calls refuse disabled views; turning off closes the current map',()=>{const f=fixture();f.load(commonSource);f.c.view='tools';f.c.commonOverviewEntry();assert.equal(f.nodes.get('#toc').children.length,0);assert.equal(f.c.showCommonOverview(),false);assert.equal(f.calls.maps,0);f.c.applyModuleOverviewEnabled('common:tools',true);f.c.commonOverviewEntry();assert.equal(f.nodes.get('#toc').children.length,1);f.c.showCommonOverview();assert.equal(f.calls.maps,1);assert.equal(f.c.lastMapHelpers.isCurrent(),true);f.c.applyModuleOverviewEnabled('common:tools',false);assert.equal(f.nodes.get('#toc').children.length,0);assert.equal(f.calls.close,1);assert.equal(f.c.lastMapHelpers.isCurrent(),false);});
test('the reduced settings styling remains jade/gold, with keyboard focus and no responsive layout additions',()=>{const css=html.slice(html.indexOf('.overview-module-settings{'),html.indexOf('#commonoverviewview{'));assert.match(css,/display:block/);assert.match(css,/--hover-gold/);assert.match(css,/:focus-visible/);assert.doesNotMatch(css,/@media/);});

test('restoration canonicalizes only equivalent Windows roots and removes conflicting case aliases',()=>{const f=fixture({'tpl_overview_preferences':JSON.stringify({schema:1,projects:{'C:/TEMP/甲':{'源代码':{enabled:false,mode:'flow'}},'D:/其他项目':{'common:auto':{enabled:true,mode:'model3d'}}}})});assert.equal(f.c.moduleOverviewEnabled('源代码'),true);const projects=JSON.parse(f.storage.get('tpl_overview_preferences')).projects;assert.equal(Object.hasOwn(projects,'C:/TEMP/甲'),false);assert.equal(projects[prefRoot]['源代码'].enabled,true);assert.equal(projects['D:/其他项目']['common:auto'].mode,'model3d');});
test('enable checkbox changes only the requested preference and keeps the surrounding settings DOM',()=>{const f=fixture(),ui=f.control('common:auto'),set=f.nodes.get('#setview');set.innerHTML='wallpaper and other unsaved settings';f.c.applyModuleOverviewMode('common:auto','flow');ui.enabled.checked=true;set.listeners.change[0]({target:ui.enabled});assert.equal(f.c.moduleOverviewEnabled('common:auto'),true);assert.equal(ui.mode.value,'flow');assert.equal(set.innerHTML,'wallpaper and other unsaved settings');assert.equal(f.calls.requests.length,0);assert.equal(f.c.moduleOverviewEnabled('common:tools'),false);});
