const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {mountHeightControl}=require('../../治理界面.js');

function fixture(storage=new Map(),scope='blueprint') {
  let full=false,current=true,resizeCount=0;
  const listeners=new Map(),captures=new Set();
  const target={dataset:{},style:{},clientHeight:560,ownerDocument:{defaultView:{localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)}}},getBoundingClientRect(){return {height:Number.parseFloat(this.style['--overview-frame-height'])||560};}};
  const handle={hidden:false,addEventListener:(k,fn)=>listeners.set(k,fn),removeEventListener:k=>listeners.delete(k),setPointerCapture:id=>captures.add(id),releasePointerCapture:id=>captures.delete(id)};
  const emit=(type,data={})=>listeners.get(type)?.({preventDefault(){},...data});
  const ctl=mountHeightControl({target,handle,projectRoot:'C:/临时/甲',scope,isFullscreen:()=>full,isCurrent:()=>current,onResize:()=>resizeCount++});
  return {target,handle,ctl,storage,listeners,captures,emit,setFull:x=>full=x,setCurrent:x=>current=x,count:()=>resizeCount};
}
function drag(f,delta,id=1){f.emit('pointerdown',{button:0,pointerId:id,clientY:100});f.emit('pointermove',{pointerId:id,clientY:100+delta});f.emit('pointerup',{pointerId:id});}

test('drag grows/shrinks the actual container style and saves only on release',()=>{
  const f=fixture();f.emit('pointerdown',{button:0,pointerId:1,clientY:100});f.emit('pointermove',{pointerId:1,clientY:360});assert.equal(f.target.style['--overview-frame-height'],'820px');assert.equal(f.storage.size,0);f.emit('pointerup',{pointerId:1});assert.equal(f.storage.get(f.ctl.state().key),'820');drag(f,-150);assert.equal(f.ctl.state().height,670);assert.equal(f.count(),2);assert.equal(f.captures.size,0);
});
test('height remains usable within 320–2400 and keyboard permits precise adjustment',()=>{const f=fixture();drag(f,-9999);assert.equal(f.ctl.state().height,320);f.emit('keydown',{key:'ArrowDown'});assert.equal(f.ctl.state().height,328);f.emit('keydown',{key:'ArrowDown',shiftKey:true});assert.equal(f.ctl.state().height,360);f.emit('keydown',{key:'ArrowLeft'});assert.equal(f.ctl.state().height,360);drag(f,9999);assert.equal(f.ctl.state().height,2400);});
test('refresh reloads explicit height, while another project or overview does not inherit it',()=>{const f=fixture();drag(f,100);const next=fixture(f.storage);assert.equal(next.ctl.state().height,660);const jade=fixture(f.storage,'archives:jade3d');assert.equal(jade.ctl.state().height,null);next.ctl.update('C:/临时/乙','blueprint');assert.equal(next.ctl.state().height,null);assert.equal(next.target.style['--overview-frame-height'],undefined);next.ctl.update('C:/临时/甲','blueprint');assert.equal(next.ctl.state().height,660);});
test('same-scope updates preserve current size and active pointer; changed scope cancels it',()=>{const f=fixture();drag(f,70);f.emit('pointerdown',{button:0,pointerId:4,clientY:0});f.ctl.update('C:/临时/甲','blueprint');f.emit('pointermove',{pointerId:4,clientY:20});assert.equal(f.ctl.state().height,650);f.ctl.update('C:/临时/乙','blueprint');f.emit('pointermove',{pointerId:4,clientY:200});assert.equal(f.ctl.state().height,null);assert.equal(f.captures.size,0);});
test('fullscreen hides corner and ends capture without saving fullscreen dimensions',()=>{const f=fixture();drag(f,100);f.emit('pointerdown',{button:0,pointerId:3,clientY:0});f.setFull(true);f.ctl.sync();assert.equal(f.handle.hidden,true);assert.equal(f.captures.size,0);f.emit('pointermove',{pointerId:3,clientY:900});f.emit('keydown',{key:'ArrowDown'});assert.equal(f.ctl.state().height,660);assert.equal(f.storage.get(f.ctl.state().key),'660');f.setFull(false);f.ctl.sync();assert.equal(f.handle.hidden,false);assert.equal(f.ctl.state().height,660);});
test('wrong pointer, non-left input, invalid coordinates and departed pages do not resize',()=>{const f=fixture();f.emit('pointerdown',{button:2,pointerId:1,clientY:0});f.emit('pointermove',{pointerId:1,clientY:500});assert.equal(f.ctl.state().height,null);f.emit('pointerdown',{button:0,pointerId:1,clientY:0});f.emit('pointermove',{pointerId:2,clientY:500});f.emit('pointermove',{pointerId:1,clientY:NaN});assert.equal(f.ctl.state().height,null);f.setCurrent(false);f.emit('pointermove',{pointerId:1,clientY:500});assert.equal(f.ctl.state().height,null);assert.equal(f.captures.size,0);});
test('untrusted persisted values do not become layout sizes',()=>{for(const raw of ['NaN','Infinity','{}','null','-10','999999','0','320px']){const storage=new Map([['tpl_overview_height:'+JSON.stringify(['C:/临时/甲','blueprint']),raw]]);const f=fixture(storage);assert.equal(f.ctl.state().height,null);assert.equal(f.target.dataset.overviewSized,undefined);}});
test('blocked localStorage still supports drag and keyboard without writing project files',()=>{const f=fixture();Object.defineProperty(f.target.ownerDocument.defaultView,'localStorage',{get(){throw Error('blocked');}});f.ctl.update('C:/临时/乙','blueprint');drag(f,100);f.emit('keydown',{key:'ArrowUp'});assert.equal(f.ctl.state().height,652);});
test('destroy releases capture and removes every handler; late events are inert',()=>{const f=fixture();f.emit('pointerdown',{button:0,pointerId:5,clientY:0});f.ctl.destroy();assert.equal(f.captures.size,0);assert.equal(f.listeners.size,0);f.emit('pointermove',{pointerId:5,clientY:500});assert.equal(f.ctl.state().height,null);f.ctl.destroy();});
test('Jade tree calls the shared control, retains its existing ResizeObserver, and never refits on height changes',()=>{const root=path.join(__dirname,'../..'),source=fs.readFileSync(path.join(root,'工具库/下载/世界树玉树/renderer.js'),'utf8'),html=fs.readFileSync(path.join(root,'模板.html'),'utf8');assert.match(html,/mountHeightControl:window.GovMap&&GovMap.mountHeightControl/);assert.match(source,/scope:'archives:jade3d'/);assert.match(source,/height:var\(--overview-frame-height,min\(72vh,46rem\)\)/);const resize=source.slice(source.indexOf('const resize=()=>'),source.indexOf('const observer=new ResizeObserver'));assert.match(resize,/renderer.setSize/);assert.doesNotMatch(resize,/(?:cameraFit|rebuild|dispose)\(/);assert.match(source,/heightControl\?\.destroy\(\)/);assert.match(source,/frameHeight:heightControl\?\.state\(\).height/);});
