'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../../模板.html'),'utf8');
const reading=html.slice(html.indexOf('/* ================= 通用读取事务 Common route reading ================= */'),html.indexOf('/* ================= 通用读取事务 Common route reading 结束 ================= */'));
const code=reading+html.slice(html.indexOf('/* ================= 技能 Skills：'),html.indexOf('/* ================= 问答 Q&A：'));
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{resolve,promise}};
test('actual success waits for flame convergence before replacing the reading body',async()=>{const f=fixture();await load(f);const merge=deferred();let completions=0;f.c.completeReading=()=>{completions++;return merge.promise};f.c.reply={...item(),text:'实际正文'};f.run('SKSEL=SK[0].id');const work=f.c.renderSkills();await new Promise(setImmediate);assert.equal(completions,1);assert.notEqual(f.ids.get('#skbody').innerHTML,'MD:实际正文');merge.resolve();await work;assert.equal(f.ids.get('#skbody').innerHTML,'MD:实际正文');});
test('read errors do not play a success convergence',async()=>{const f=fixture();await load(f);f.c.completeReading=()=>{throw Error('False success')};f.c.api=async()=>{throw Error('真实读取失败')};f.run('SKSEL=SK[0].id');await f.c.renderSkills();assert.match(f.ids.get('#skbody').innerHTML,/role="alert".*真实读取失败/);});
test('a project change during convergence cannot replace the new project body',async()=>{const f=fixture();await load(f);const merge=deferred();f.c.completeReading=()=>merge.promise;f.c.reply={...item(),text:'旧项目正文'};f.run('SKSEL=SK[0].id');const work=f.c.renderSkills();await new Promise(setImmediate);f.c.S={project:{root:'C:/TEMP/乙'}};f.c.skReset('C:/TEMP/乙');f.ids.get('#skbody').innerHTML='新项目';merge.resolve();await work;assert.equal(f.ids.get('#skbody').innerHTML,'新项目');});
class SkillElement{
  constructor(tag='div',id='',registry=null){this.registry=registry;this.tagName=tag.toUpperCase();this.id=id;this.children=[];this.parentNode=null;this.dataset={};this.attributes={};this.listeners={};this._html='';this.writeCount=0;this.scrollTop=0;this.value='';}
  get isConnected(){return this.tagName==='BODY'||!!(this.parentNode&&this.parentNode.isConnected);}
  get firstElementChild(){return this.children[0]||null;}
  get innerHTML(){return this._html+this.children.filter(n=>!n.placeholder).map(n=>n.outerHTML).join('');}
  set innerHTML(value){this._html=String(value);++this.writeCount;this.children.forEach(c=>c.parentNode=null);this.children=[];
    for(const m of this._html.matchAll(/<([a-z]+)\b([^>]*\bid="([^"]+)"[^>]*)>/gi)){const n=new SkillElement(m[1],m[3],this.registry);n.placeholder=true;for(const a of m[2].matchAll(/([\w-]+)="([^"]*)"/g))n.setAttribute(a[1],a[2].replaceAll('&amp;','&'));this.appendChild(n);if(this.registry)this.registry.set('#'+n.id,n);}}
  get outerHTML(){return '<'+this.tagName.toLowerCase()+Object.entries(this.attributes).map(([k,v])=>' '+k+'="'+v+'"').join('')+'>'+this.innerHTML+'</'+this.tagName.toLowerCase()+'>';}
  setAttribute(k,v){this.attributes[k]=String(v);if(k==='id')this.id=String(v);}getAttribute(k){return this.attributes[k]||null;}
  appendChild(n){if(n.parentNode)n.remove();n.parentNode=this;this.children.push(n);return n;}
  remove(){if(this.parentNode){this.parentNode.children.splice(this.parentNode.children.indexOf(this),1);this.parentNode=null;}}
  contains(n){return this===n||this.children.some(c=>c.contains(n));}
  addEventListener(k,f){(this.listeners[k]??=[]).push(f);}
  querySelector(s){return this.querySelectorAll(s)[0]||null;}
  querySelectorAll(s){const out=[];const walk=n=>n.children.forEach(c=>{if(s[0]==='#'&&c.id===s.slice(1))out.push(c);walk(c);});walk(this);return out;}
}
function fixture(){
  const ids=new Map(), storage=new Map(),calls=[];
  const body=new SkillElement('body','',ids);
  ['#toc','#skillsview','#skbody','#skmetadata'].forEach(id=>{const node=new SkillElement('div',id.slice(1),ids);ids.set(id,node);body.appendChild(node);});
  const c={S:{project:{root:'C:/TEMP/甲',name:'一般项目'}},view:'skills',online:true,document:{activeElement:null,title:'',body,createElement:tag=>new SkillElement(tag,'',ids)},location:{hash:'#/skills'},URL,console,encodeURIComponent,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},window:{scrollTo(){}},getLang:()=>c.lang||'zh',esc:s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),uiIcon:()=>'<svg/>',$:s=>ids.get(s),setToc(){},toast(){},appendNote(){throw Error('Unexpected note write')},installThing(){throw Error('Unexpected installation')},renderMd:x=>'MD:'+x,api:async(m,p,b)=>{calls.push({m,p,b});return c.reply||{schema:1,groups:[],items:[],issues:[]}}};
  c.readingFlames=zh=>zh;
  c.completeReading=async()=>{};
  c.failReading=(host,zh)=>{host.innerHTML='<span role="alert">'+c.esc(zh)+'</span>';};
  vm.createContext(c);vm.runInContext(code,c);return{c,ids,calls,run:s=>vm.runInContext(s,c)};
}
const item=(id='biz:sample:vendor:entry')=>({id,kind:'skill',name:'研究步骤',title:{'zh-CN':'研究步骤',en:'Research step'},description:'证据方法',summary:{'zh-CN':'本地记录',en:'Local record'},business:'sample',stages:['a','b'],available:true,installable:true,languages:{'zh-CN':'技能库/业务/a/SKILL.md',en:'技能库/业务/a/SKILL.en.md'},source:{repo:'owner/repository'},issues:[],package_revision:'one'});
const group=()=>({id:'sample',title:{'zh-CN':'临时路线',en:'Temporary route'},summary:{'zh-CN':'不写死科研',en:'Generic route'},entry:'biz:sample:vendor:entry',stages:[{id:'a',order:1,title:{'zh-CN':'准备',en:'Prepare'},inputs:{'zh-CN':'资料',en:'Materials'},outputs:{'zh-CN':'记录',en:'Record'},acceptance:{'zh-CN':'可追溯',en:'Traceable'},continue_when:{'zh-CN':'明确',en:'Clear'}},{id:'b',order:2,title:{'zh-CN':'复核',en:'Verify'}}]});
async function load(f,items=[item()],groups=[group()]){f.c.reply={schema:1,groups,items,issues:[]};await f.c.showSkills();}
test('inventory loading is read-only and does not install, write notes or start workers',async()=>{const f=fixture();await load(f);assert.deepEqual(f.calls.map(x=>[x.m,x.p]),[['GET','api/skills/catalog']]);assert.match(f.ids.get('#skillsview').innerHTML,/临时路线/);});
test('general project with no business has no invented business or research card',async()=>{const f=fixture();await load(f,[],[]);assert.doesNotMatch(f.ids.get('#skillsview').innerHTML,/写论文|写小说|剪辑/);assert.match(f.ids.get('#skillsview').innerHTML,/技能库是空的/);});
test('one canonical item can appear in two stage routes without a second copied source',async()=>{const f=fixture();await load(f);assert.equal(f.run('SK.length'),1);assert.match(f.c.skRoute(group(),group().stages[0]),/biz:sample:vendor:entry/);assert.match(f.c.skRoute(group(),group().stages[1]),/biz:sample:vendor:entry/);});
test('stage route exposes inputs, outputs, acceptance and continuation in English',async()=>{const f=fixture();f.c.lang='en';await load(f);const s=f.c.skRoute(group(),group().stages[0]);for(const text of ['Inputs','Materials','Outputs','Record','Acceptance','Traceable','Continue when','Clear'])assert.ok(s.includes(text));});
test('search matches English titles, complete IDs and source repositories',()=>{const f=fixture();f.run("SKSEARCH='research step'");assert.equal(f.c.skMatches(item()),true);f.run("SKSEARCH='owner/repository'");assert.equal(f.c.skMatches(item()),true);f.run("SKSEARCH='biz:sample:vendor'");assert.equal(f.c.skMatches(item()),true);f.run("SKSEARCH='does-not-exist'");assert.equal(f.c.skMatches(item()),false);});
test('link-only and incomplete records never get a green builtin state or install actions',async()=>{for(const record of [{...item(),kind:'link',available:false,installable:false,languages:{}},{...item(),available:false,installable:false}]){const f=fixture();await load(f,[record]);f.c.reply={...record,text:'Source information',source:{url:'https://example.org/source'}};f.run('SKSEL=SK[0].id');await f.c.renderSkills();const body=f.ids.get('#skillsview').innerHTML;assert.doesNotMatch(body,/data-inst|data-fork|内置可用/);assert.match(body,/外部链接|资料不完整/);}});
test('unsafe, credential-bearing and script source URLs cannot become links',()=>{const f=fixture();for(const url of ['javascript:alert(1)','file:///tmp/a','https://user:secret@example.org'])assert.equal(f.c.skLink(url,'Source'),'');assert.match(f.c.skLink('https://example.org/a','Source'),/noopener noreferrer/);});
test('source and license data are escaped, source links need an explicit click',()=>{const f=fixture();const h=f.c.skDetails({path:'<bad>',source:{repo:'<repo>',url:'https://example.org'},license:{id:'MIT',files:['技能库/LICENSE']},dependencies:[],issues:[]});assert.ok(h.includes('&lt;repo&gt;'));assert.ok(h.includes('data-peek="技能库/LICENSE"'));assert.doesNotMatch(h,/<repo>/);});
test('older inventory response cannot overwrite a newer refresh',async()=>{const f=fixture(),a=deferred(),b=deferred();let n=0;f.c.api=()=>++n===1?a.promise:b.promise;const one=f.c.showSkills(),two=f.c.showSkills();b.resolve({items:[item('new')],groups:[],issues:[]});await two;a.resolve({items:[item('old')],groups:[],issues:[]});await one;assert.equal(f.run('SK[0].id'),'new');});
test('old project response cannot populate another project after switching',async()=>{const f=fixture(),a=deferred();f.c.api=()=>a.promise;const pending=f.c.showSkills();f.c.S={project:{root:'C:/TEMP/乙',name:'Another'}};f.c.skReset('C:/TEMP/乙');a.resolve({items:[item()],groups:[group()],issues:[]});await pending;assert.equal(f.run('SK.length'),0);});
test('late Chinese read cannot overwrite the selected English body',async()=>{const f=fixture();await load(f);const a=deferred(),b=deferred();let n=0;f.c.api=()=>++n===1?a.promise:b.promise;f.run('SKSEL=SK[0].id');const first=f.c.renderSkills();f.run("SKLANG='en'");const second=f.c.renderSkills();b.resolve({...item(),text:'English actual'});await second;a.resolve({...item(),text:'中文旧响应'});await first;assert.equal(f.ids.get('#skbody').innerHTML,'MD:English actual');});
test('refresh with unchanged source keeps the open reading DOM and avoids repeated detail reads',async()=>{const f=fixture();await load(f);f.c.reply={...item(),text:'正文'};f.run('SKSEL=SK[0].id');await f.c.renderSkills();const before=f.calls.length,dom=f.ids.get('#skillsview').innerHTML;await f.c.renderSkills();assert.equal(f.calls.length,before);assert.equal(f.ids.get('#skillsview').innerHTML,dom);});
test('source revision change rereads the same selected skill',async()=>{const f=fixture();await load(f);f.c.reply={...item(),text:'第一版'};f.run('SKSEL=SK[0].id');await f.c.renderSkills();f.run("SK[0].package_revision='two'");f.c.reply={...item(),text:'第二版'};await f.c.renderSkills();assert.equal(f.ids.get('#skbody').innerHTML,'MD:第二版');});
test('full identifiers and languages are encoded in detail route',async()=>{const f=fixture();await load(f);f.c.reply={...item(),text:'en'};f.run("SKSEL=SK[0].id;SKLANG='en'");await f.c.renderSkills();assert.equal(f.calls.at(-1).p,'api/skills/biz%3Asample%3Avendor%3Aentry?language=en');});
test('document references open the current project source path; fenced code stays literal',()=>{const f=fixture();const start=html.indexOf('function renderMd(src,'),end=html.indexOf('/* ================= 外部资料入口 Intake',start);f.c.pathish=()=>false;vm.runInContext(html.slice(start,end),f.c);const doc='技能库/业务/video/vendor/entry/SKILL.md';const result=f.c.renderMd('[SOURCE.md](<SOURCE.md>)\n\n[原文](../../../sources/vendor/SKILL.md)\n\n```md\n[x](file.md)\n```',doc);assert.match(result,/data-peek="技能库\/业务\/video\/vendor\/entry\/SOURCE.md"/);assert.match(result,/data-peek="技能库\/业务\/sources\/vendor\/SKILL.md"/);assert.match(result,/<pre[^>]*>\[x\]\(file.md\)<\/pre>/);assert.doesNotMatch(f.c.renderMd('[x](../../../../../../../outside.md)',doc),/data-peek/);assert.doesNotMatch(f.c.renderMd('[x](javascript:alert)',doc),/href="javascript/);});
test('Markdown views without a source path retain their existing output',()=>{const f=fixture();const start=html.indexOf('function renderMd(src,'),end=html.indexOf('/* ================= 外部资料入口 Intake',start);f.c.pathish=()=>false;vm.runInContext(html.slice(start,end),f.c);assert.equal(f.c.renderMd('[local](SOURCE.md)'),'\x3cp>[local](SOURCE.md)</p>');});
