'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const template=fs.readFileSync(path.join(__dirname,'../../模板.html'),'utf8'),staged=!!process.env.MH_FILE_DELETE_UI_SOURCE;
const full=staged?fs.readFileSync(process.env.MH_FILE_DELETE_UI_SOURCE,'utf8'):template;
function extract(text,start,end){const a=text.indexOf(start),b=text.indexOf(end,a);assert.ok(a>=0&&b>a,'Missing production function block '+start);return text.slice(a,b);}
const code=extract(template,'function builtinFileSlot(','const BuiltinFiles=')+'\n'+extract(template,'/* ================= 模块读取事务 Module loading ================= */','/* ================= 模块读取事务 Module loading 结束 ================= */')+'\n'
  +extract(full,'/* ================= 阅读页删除 File delete UI ================= */','/* ================= 阅读页删除 File delete UI 结束 ================= */')+'\n'
  +['showFile','showModule'].map(fn=>extract(full,'/* 模块读取入口 '+fn+' */','/* 模块读取入口 '+fn+' 结束 */')).join('\n')+'\n'
  +['previewProject','loadPTree'].map(fn=>extract(full,'/* 阅读页删除入口 '+fn+' */','/* 阅读页删除入口 '+fn+' 结束 */')).join('\n');
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function decode(s){return String(s).replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');}
class Element{
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.parentNode=null;this.dataset={};this.attributes={};this.value='';this.disabled=false;this.hidden=false;this._html='';this.writes=0;this.events={};this.textContent='';this.scrollTop=0;const cs=new Set();this.classList={add:(...xs)=>xs.forEach(x=>cs.add(x)),remove:(...xs)=>xs.forEach(x=>cs.delete(x)),contains:x=>cs.has(x),toggle:(x,v)=>{const yes=v===undefined?!cs.has(x):!!v;yes?cs.add(x):cs.delete(x);return yes;}};}
  get isConnected(){let n=this;while(n){if(n.tagName==='BODY')return true;n=n.parentNode;}return false;}
  get firstElementChild(){return this.children[0]||null;}
  get innerHTML(){return this._html;}
  set innerHTML(html){this._html=String(html);++this.writes;for(const c of [...this.children])c.remove();const stack=[this];for(const m of this._html.matchAll(/<\/?[A-Za-z][^>]*>/g)){const token=m[0];if(token.startsWith('</')){if(stack.length>1)stack.pop();continue;}const tag=token.match(/^<([A-Za-z0-9]+)/)[1],n=new Element(tag);for(const a of token.matchAll(/([\w-]+)(?:="([^"]*)")?/g)){if(a.index===1)continue;n.setAttribute(a[1],decode(a[2]||''));}stack.at(-1).appendChild(n);if(!/^(input|img|hr|br|meta|link)$/i.test(tag)&&!token.endsWith('/>'))stack.push(n);}}
  appendChild(n){if(n.parentNode)n.remove();n.parentNode=this;this.children.push(n);return n;}
  remove(){if(this.parentNode){this.parentNode.children.splice(this.parentNode.children.indexOf(this),1);this.parentNode=null;}}
  setAttribute(k,v){this.attributes[k]=String(v);if(k==='id')this.id=v;if(k==='class')String(v).split(/\s+/).forEach(c=>this.classList.add(c));if(k==='disabled')this.disabled=true;if(k==='value')this.value=v;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=v;}
  getAttribute(k){return this.attributes[k]??null;}
  contains(n){return this===n||this.children.some(c=>c.contains(n));}
  matches(s){const attrs=[...s.matchAll(/\[([^\]=]+)(?:="([^"]*)")?\]/g)],base=s.replace(/\[[^\]]*\]/g,'');if(base[0]==='#'&&this.id!==base.slice(1))return false;if(base[0]==='.'&&!base.slice(1).split('.').every(c=>this.classList.contains(c)))return false;if(base&&base[0]!=='.'&&base[0]!=='#'&&this.tagName.toLowerCase()!==base)return false;return attrs.every(a=>a[2]===undefined?Object.hasOwn(this.attributes,a[1]):this.attributes[a[1]]===a[2]);}
  querySelectorAll(s){const out=[];const walk=n=>n.children.forEach(c=>{if(c.matches(s))out.push(c);walk(c);});walk(this);return out;}
  querySelector(s){return this.querySelectorAll(s)[0]||null;}
}
const root='C:/Synthetic/Alpha',canonical='治理/需求/模块甲.md',version='a'.repeat(64);
function action(extra={}){return{allowed:true,path:canonical,project:root.toLowerCase(),revision:version,reason:'',...extra};}
function preview(extra={}){return{kind:'text',text:'保留的原文',size:20,mtime:'2026-10-05',delete_action:action(),...extra};}
function result(extra={}){return{code:'X27',from:[canonical],to:'回收站/2026-10-05 X27/'+canonical,status:'在回收站',record_path:'回收站/清单.md',log_id:'志-0123',...extra};}
function harness(scope='module'){
  const e={requests:[],toasts:[],prompts:[],completed:[],completionWaits:[],hold:false,promptValue:'用户填写的删除原因',renderedTrees:[],opened:[],body:new Element('body')};
  for(const id of ['tree','modview','searchview','ptree','sres','spv','sq']){const n=new Element(id==='sq'?'input':'div');n.id=id;e[id]=n;e.body.appendChild(n);}e.sq.value='查询';
  const c={console,Set,WeakMap,JSON,Promise,encodeURIComponent,S:{project:{root,name:'Alpha'},modules:[{name:'A',files:2}]},view:scope==='module'?'mod':'search',cur:scope==='module'?'A':null,online:true,MV:{name:'A',sel:null,shown:null,tree:null,open:new Set()},PV:{tree:null,sel:null,open:new Set()},PCACHE:{},CMAPCTL:null,ZPOS:{},LASTFILE:{},scrollY:7,ACT:{viewed:[]},MODULEMAP:'#模块总览',OPENABLE_KINDS:['text'],ZEN:{slide:null},location:{hash:scope==='module'?'#/m/A':'#/search'},history:{replaceState:(a,b,url)=>{c.location.hash=url;}},document:{createElement:tag=>new Element(tag)},window:{},$:s=>e.body.querySelector(s),esc,getLang:()=>e.lang||'zh',
    readingFlames:(zh,en)=>'<span>'+((e.lang==='en')?en:zh)+'</span>',completeReading:async n=>{assert.ok(n.isConnected);e.completed.push(n);if(e.hold){const w=deferred();e.completionWaits.push(w);await w.promise;}},
    api:(method,url,data)=>{if(method==='POST'){assert.equal(url,'api/files/trash');assert.deepEqual(Object.keys(data).sort(),['path','project','reason','revision']);}else{assert.equal(method,'GET');assert.ok(/^api\/modules\/[^/]+\/(preview\?path=|tree)/.test(url)||/^api\/project\/(preview\?path=|tree)/.test(url),url);}const w=deferred();e.requests.push({method,url,data,...w});return w.promise;},
    prompt:(text,value)=>{e.prompts.push({text,value});if(e.onPrompt)e.onPrompt();return e.promptValue;},toast:s=>e.toasts.push(String(s)),
    shown:p=>p.startsWith('@/')?p.slice(2):'资料/'+c.cur+'/'+p,rawUrl:(name,p)=>'files/'+name+'/'+p,
    previewBody:p=>({body:'<article>'+esc(p.text)+'</article>',wide:!!p.wide}),pvWrap:s=>s,fmtSize:s=>String(s),fmtTime:s=>String(s),govButton:()=>'',stickyNoteIcon:()=>'<svg></svg>',
    act:(array,x)=>array.push(x),zkey:(m,p)=>m+'|'+p,fileHash:p=>c.location.hash='#/m/'+c.cur+'?f='+encodeURIComponent(p),landOn:(name,p)=>c.MV.shown=p,modHref:name=>'#/m/'+name,
    appendNote(){},openLocal(){},renderTree:m=>{e.renderedTrees.push(c.MV.tree);},moduleOverviewEnabled:()=>false,isModuleOverviewPath:p=>p==='#模块总览',moduleDefaultFile:()=> 'another.md',moduleOverviewPath:()=> '#模块总览',renderIntro:()=>e.modview.innerHTML='<p>Intro</p>',
    openItem:p=>e.opened.push(p),zenOn:()=>false,zenLand(){},zenPos(){},zenPrefetch(){},pnodes:xs=>xs.map(x=>'<span>'+esc(x.name)+'</span>').join('')};
  c.window=c;vm.createContext(c);vm.runInContext(code,c);e.c=c;e.eval=s=>vm.runInContext(s,c);e.state=()=>e.eval('FILE_DELETE');e.call=(fn,...args)=>c[fn](...args);e.node=(selector,scope=e.modview)=>scope.querySelector(selector);
  e.leave=()=>{c.invalidateModuleReading();c.fileDeleteRelease();c.view='settings';c.cur=null;c.location.hash='#/settings';};
  e.root=()=>{c.S={...c.S,project:{root:'C:/Synthetic/Beta',name:'Beta'}};c.moduleReadProjectChanged();c.fileDeleteProjectChanged();};
  return e;
}
const tick=()=>new Promise(a=>setImmediate(a));async function until(fn){for(let i=0;i<30&&!fn();i++)await tick();assert.ok(fn(),'Expected production awaited operation');}
async function readModule(e,p=preview(),path='@/资料/旧模块/需求.md'){const pending=e.call('showFile',path);e.requests.at(-1).resolve(p);await pending;return e.node('[data-file-delete]');}
async function readProject(e,p=preview(),path='旧需求.md'){const pending=e.call('previewProject',path);e.requests.at(-1).resolve(p);await pending;return e.node('[data-file-delete]',e.spv);}
async function deletedModule(e,button,r=result()){const pending=e.call('fileDeleteRequest',button);e.requests.at(-1).resolve(r);await until(()=>e.requests.at(-1).method==='GET'&&e.requests.at(-1).url.endsWith('/tree'));e.requests.at(-1).resolve({items:[],name:'A'});await pending;return pending;}
test('cancel is zero writes and prompt names server canonical path with recoverability and editable reason',async()=>{const e=harness(),button=await readModule(e);e.promptValue=null;const count=e.requests.length;assert.equal(await e.call('fileDeleteRequest',button),false);assert.equal(e.requests.length,count);assert.equal(e.prompts.length,1);assert.ok(e.prompts[0].text.includes(canonical));assert.match(e.prompts[0].text,/可以还原/);assert.equal(e.prompts[0].value,'人在文件阅读页手工删除');assert.match(e.modview.innerHTML,/保留的原文/);});
test('only complete server metadata enables delete; protected reason is shown safely and cannot be bypassed',async()=>{for(const patch of [{allowed:false,reason:'笔记原文不能删 <script>'},{project:''},{project:'C:/Wrong'},{revision:''},{revision:'fake'},{path:'../outside'},{projectroot:root,project:undefined}]){const e=harness(),button=await readModule(e,preview({delete_action:action(patch)}));assert.equal(button.disabled,true);assert.equal(await e.call('fileDeleteRequest',button),false);assert.equal(e.prompts.length,0);assert.equal(e.requests.length,1);assert.doesNotMatch(e.modview.innerHTML,/<script>/);}});
test('POST sends server canonical path/project/version/user reason only, never client roles or guessed old aliases',async()=>{const e=harness(),button=await readModule(e);const pending=e.call('fileDeleteRequest',button),req=e.requests.at(-1);assert.equal(req.method,'POST');assert.equal(req.data.path,canonical);assert.equal(req.data.project,root.toLowerCase());assert.equal(req.data.revision,version);assert.equal(req.data.reason,'用户填写的删除原因');assert.deepEqual(Object.keys(req.data).sort(),['path','project','reason','revision']);req.reject(Error('version changed'));await pending;assert.match(e.toasts[0],/version changed/);});
test('duplicate clicks while POST is pending submit exactly once, preserve original page, then success is recoverable',async()=>{const e=harness(),button=await readModule(e),old=e.modview.innerHTML;const pending=e.call('fileDeleteRequest',button);assert.equal(button.disabled,true);assert.equal(await e.call('fileDeleteRequest',button),false);assert.equal(e.requests.filter(x=>x.method==='POST').length,1);assert.equal(e.modview.innerHTML,old);e.requests.at(-1).resolve(result());await until(()=>e.requests.at(-1).url.endsWith('/tree'));assert.match(e.modview.innerHTML,/X27/);assert.match(e.modview.innerHTML,/可还原/);assert.match(e.modview.innerHTML,/href="#\/trash"/);assert.equal(e.c.location.hash,'#/m/A');assert.equal(e.c.MV.sel,null);e.requests.at(-1).resolve({items:[]});assert.equal(await pending,true);assert.equal(e.opened.length,0);});
test('file version conflict or network failure retains original iframe/input/content and re-enables the current button',async()=>{for(const message of ['文件在打开后发生变化','Network failed']){const e=harness(),button=await readModule(e),input=new Element('input'),frame=new Element('iframe');input.value='未保存';frame.src='existing';e.modview.appendChild(input);e.modview.appendChild(frame);const old=e.modview.innerHTML,pending=e.call('fileDeleteRequest',button);e.requests.at(-1).reject(Error(message));assert.equal(await pending,false);assert.equal(e.modview.innerHTML,old);assert.equal(input.value,'未保存');assert.ok(e.modview.contains(input)&&e.modview.contains(frame));assert.equal(button.disabled,false);assert.equal(e.requests.filter(x=>x.method==='GET').length,1);assert.equal(e.c.MV.sel,'@/资料/旧模块/需求.md');}});
test('empty or oversized reason is rejected locally before any POST',async()=>{for(const value of ['', ' '.repeat(4),'x'.repeat(2001)]){const e=harness(),button=await readModule(e);e.promptValue=value;assert.equal(await e.call('fileDeleteRequest',button),false);assert.equal(e.requests.length,1);assert.match(e.toasts[0],/原因/);}});
test('stale button and context changes inside native prompt never send deletion',async()=>{for(const change of ['root','view','path','hash','serial','host']){const e=harness(),button=await readModule(e);e.onPrompt=()=>{if(change==='root')e.root();else if(change==='view')e.leave();else if(change==='path')e.c.MV.sel='other.md';else if(change==='hash')e.c.location.hash='#/other';else if(change==='serial')e.eval('++FILE_DELETE.serial');else{e.modview.remove();const n=new Element();n.id='modview';e.body.appendChild(n);}};assert.equal(await e.call('fileDeleteRequest',button),false,change);assert.equal(e.requests.filter(x=>x.method==='POST').length,0,change);}});
test('late success and failure after changing root/view/path cannot clear or toast in another page',async()=>{for(const resultKind of ['success','error']){const e=harness(),button=await readModule(e),pending=e.call('fileDeleteRequest',button),req=e.requests.at(-1);e.root();e.modview.innerHTML='<input value="other project">';if(resultKind==='success')req.resolve(result());else req.reject(Error('old error'));await pending;assert.match(e.modview.innerHTML,/other project/);assert.equal(e.toasts.length,0);assert.equal(e.requests.length,2);}});
test('module success clears selected/shown/last file and only current-root preview cache, refreshes tree without opening another file',async()=>{const e=harness(),button=await readModule(e),path=e.c.MV.sel;e.c.PCACHE[JSON.stringify([root,'A',path])]='old';e.c.PCACHE[JSON.stringify(['C:/Other','A',path])]='other';await deletedModule(e,button);assert.equal(e.c.MV.sel,null);assert.equal(e.c.MV.shown,null);assert.equal(e.c.LASTFILE.A,undefined);assert.equal(e.c.PCACHE[JSON.stringify([root,'A',path])],undefined);assert.equal(e.c.PCACHE[JSON.stringify(['C:/Other','A',path])],'other');assert.equal(e.requests[2].url,'api/modules/A/tree');assert.equal(e.renderedTrees.length,1);assert.equal(e.opened.length,0);assert.equal(e.c.location.hash,'#/m/A');});
test('module watcher during pending write does not invalidate the requested delete or restart file reading',async()=>{const e=harness(),button=await readModule(e),pending=e.call('fileDeleteRequest',button);const count=e.requests.length,resultWaiting=await e.call('showModule');assert.equal(resultWaiting.scope,'file-delete-pending');assert.equal(e.requests.length,count);e.requests.at(-1).resolve(result());await until(()=>e.requests.at(-1).url.endsWith('/tree'));e.requests.at(-1).resolve({items:[]});assert.equal(await pending,true);assert.match(e.modview.innerHTML,/X27/);});
test('after success later module directory refresh preserves the X result tombstone and never selects a default file',async()=>{const e=harness(),button=await readModule(e);await deletedModule(e,button);const old=e.modview.innerHTML,pending=e.call('showModule');e.requests.at(-1).resolve({items:[{name:'another',path:'another.md'}]});await pending;assert.equal(e.modview.innerHTML,old);assert.equal(e.opened.length,0);assert.equal(e.call('fileDeleteHoldModule'),true);e.call('fileDeleteRelease');assert.equal(e.call('fileDeleteHoldModule'),false);});
test('late tree-only module response after navigation cannot replace the new page or directory',async()=>{const e=harness(),button=await readModule(e),pending=e.call('fileDeleteRequest',button);e.requests.at(-1).resolve(result());await until(()=>e.requests.at(-1).url.endsWith('/tree'));const req=e.requests.at(-1);e.leave();e.modview.innerHTML='<p>new page</p>';req.resolve({items:[{name:'old'}]});await pending;assert.match(e.modview.innerHTML,/new page/);assert.equal(e.renderedTrees.length,0);});
test('success warnings/log IDs/paths are escaped and an unconfirmed response never clears the page',async()=>{const e=harness(),button=await readModule(e);await deletedModule(e,button,result({warning:'<script>bad()</script>',log_id:'<img src=x>'}));assert.doesNotMatch(e.modview.innerHTML,/<script>|<img/);assert.match(e.modview.innerHTML,/&lt;script&gt;/);const x=harness(),b=await readModule(x),old=x.modview.innerHTML,pending=x.call('fileDeleteRequest',b);x.requests.at(-1).resolve(result({from:['different.md']}));assert.equal(await pending,false);assert.equal(x.modview.innerHTML,old);assert.match(x.toasts[0],/未确认/);});
test('project preview A→B→A uses request serials so old success/catch cannot bind a wrong delete version',async()=>{const e=harness('project'),a=e.call('previewProject','A.md'),b=e.call('previewProject','B.md'),a2=e.call('previewProject','A.md');e.requests[2].resolve(preview({text:'最新A',delete_action:action({revision:'b'.repeat(64)})}));await a2;e.requests[0].resolve(preview({text:'旧A'}));e.requests[1].reject(Error('旧B错误'));await Promise.all([a,b]);assert.match(e.spv.innerHTML,/最新A/);assert.doesNotMatch(e.spv.innerHTML,/旧A/);assert.equal(e.spv.querySelector('[data-file-delete]').fileDeleteContext.action.revision,'b'.repeat(64));assert.equal(e.toasts.length,0);});
test('project preview and completion retain old content while pending, then guard root/selection/host/hash after actual success',async()=>{for(const change of ['root','path','host','hash']){const e=harness('project');e.spv.innerHTML='<input value="typing"><iframe></iframe>';e.hold=true;const pending=e.call('previewProject','A.md'),input=e.spv.querySelector('input');e.requests[0].resolve(preview());await until(()=>e.completionWaits.length===1);assert.equal(e.spv.querySelector('input'),input);if(change==='root')e.root();else if(change==='path')e.c.PV.sel='new.md';else if(change==='hash')e.c.location.hash='#/other';else{e.spv.remove();const n=new Element();n.id='spv';e.body.appendChild(n);}e.completionWaits[0].resolve();await pending;assert.doesNotMatch(e.spv.innerHTML,/data-file-delete/);assert.equal(e.toasts.length,0);}});
test('same project preview metadata refresh keeps original DOM and safely rebinds the current version context',async()=>{const e=harness('project'),button=await readProject(e),anchor=e.spv.firstElementChild,old=button.fileDeleteContext;const again=e.call('previewProject','旧需求.md');e.requests.at(-1).resolve(preview());await again;assert.equal(e.spv.firstElementChild,anchor);assert.equal(e.spv.querySelector('[data-file-delete]'),button);assert.notEqual(button.fileDeleteContext,old);assert.equal(e.call('fileDeleteCurrent',old),false);assert.equal(e.call('fileDeleteCurrent',button.fileDeleteContext),true);});
test('project success clears PV selection, preserves recoverable X card, refreshes read-only tree and never searches or opens another file',async()=>{const e=harness('project'),button=await readProject(e),pending=e.call('fileDeleteRequest',button);e.requests.at(-1).resolve(result());await until(()=>e.requests.at(-1).url==='api/project/tree');assert.equal(e.c.PV.sel,'');assert.match(e.spv.innerHTML,/X27/);e.requests.at(-1).resolve({name:'Alpha',items:[{name:'remaining.md'}]});assert.equal(await pending,true);assert.match(e.ptree.innerHTML,/remaining.md/);assert.equal(e.opened.length,0);assert.equal(e.requests.length,3);});
test('project deletion old tree reply cannot overwrite another root or a newly chosen preview',async()=>{const e=harness('project'),button=await readProject(e),pending=e.call('fileDeleteRequest',button);e.requests.at(-1).resolve(result());await until(()=>e.requests.at(-1).url==='api/project/tree');const tree=e.requests.at(-1);e.root();e.ptree.innerHTML='<p>other root</p>';e.spv.innerHTML='<p>other preview</p>';tree.resolve({name:'old root',items:[{name:'old file'}]});await pending;assert.match(e.ptree.innerHTML,/other root/);assert.match(e.spv.innerHTML,/other preview/);assert.equal(e.toasts.length,0);});
test('ordinary project tree load rejects stale root and superseded responses without guessing task/file selection',async()=>{const e=harness('project'),a=e.call('loadPTree'),b=e.call('loadPTree');e.requests[1].resolve({name:'latest',items:[]});await b;e.requests[0].resolve({name:'old',items:[]});await a;assert.equal(e.c.PV.tree.name,'latest');const pending=e.call('loadPTree');e.root();e.requests.at(-1).resolve({name:'wrong root',items:[]});await pending;assert.equal(e.c.PV.tree.name,'latest');assert.equal(e.c.PV.sel,null);});
test('English delete prompt and result remain explicit with no hidden role fields',async()=>{const e=harness();e.lang='en';const b=await readModule(e);e.promptValue=null;await e.call('fileDeleteRequest',b);assert.match(e.prompts[0].text,/recoverable/);assert.match(e.modview.innerHTML,/>Delete</);assert.doesNotMatch(code,/next_task|api\/auto\/launch|api\/board|role\s*:/);});
test('actual template hooks release stale delete contexts and preserve X cards before automatic default opening',{skip:staged?'TEMP only; root owns template hooks':false},()=>{assert.match(template,/function render\(s\)[\s\S]{0,320}fileDeleteProjectChanged\(/);assert.match(template,/function openItem\(path, quiet\)[\s\S]{0,180}fileDeleteRelease\(/);assert.match(template,/function route\(\)[\s\S]{0,160}fileDeleteRelease\(/);assert.match(code,/MV\.tree=tree;renderTree\(m\);\s*if\(typeof fileDeleteHoldModule/);});
