'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const candidate=path.resolve(__dirname,'../../模板.html'),project=process.env.GUIDE_PROJECT_PATH|| (fs.existsSync(candidate)?path.dirname(candidate):process.cwd());
const html=fs.readFileSync(path.join(project,'模板.html'),'utf8'),tempBlock=path.join(__dirname,'guide-ui-block.js');
const code=fs.existsSync(tempBlock)?fs.readFileSync(tempBlock,'utf8'):html.slice(html.indexOf('/* ================= 使用说明（双语）'),html.indexOf('/* ================= 计划 Plans'));
const render=html.slice(html.indexOf('function renderMd('),html.indexOf('/* ================= 外部资料入口 Intake'));
const preview=process.env.GUIDE_DOC_PREVIEW||(fs.existsSync(path.join(__dirname,'guide-doc-preview/使用说明.md'))?path.join(__dirname,'guide-doc-preview'):project);
const docs={zh:fs.readFileSync(path.join(preview,'使用说明.md'),'utf8'),en:fs.readFileSync(path.join(preview,'使用说明.en.md'),'utf8')};
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{resolve,promise};};
function fixture(){
  const ids=new Map(),storage=new Map(),calls=[],scrolls=[],windowEvents={},groups=[],buttons=[];
  function element(){return {value:'',assignments:0,listeners:{},children:[],dataset:{},attributes:{},parentElement:null,addEventListener(t,fn){(this.listeners[t]??=[]).push(fn);},setAttribute(k,v){this.attributes[k]=v;},removeAttribute(k){delete this.attributes[k];},appendChild(node){this.children.push(node);if(node.id)ids.set(node.id,node);},get innerHTML(){return this.value;},set innerHTML(v){this.value=v;this.assignments++;for(const m of v.matchAll(/\bid="([^"]+)"/g)){const id=m[1];ids.set(id,{id,parentElement:null,scrollIntoView:options=>scrolls.push({id,options})});}if(this===ids.get('#toc')){groups.length=buttons.length=0;for(const m of v.matchAll(/<details[^>]*data-guide-group="([^"]+)"([^>]*)>/g))groups.push({dataset:{guideGroup:m[1]},open:/\bopen\b/.test(m[2])});for(const m of v.matchAll(/<button[^>]*class="([^"]*)"[^>]*data-guide-target="([^"]+)"/g)){const set=new Set(m[1].split(' '));buttons.push({dataset:{guideTarget:m[2]},attributes:{},classList:{toggle:(k,on)=>on?set.add(k):set.delete(k),contains:k=>set.has(k)},setAttribute(k,v){this.attributes[k]=v;},removeAttribute(k){delete this.attributes[k];}});}}},querySelector(s){return s==='.guide-body'&&this.value.includes('guide-body')?this:null;},querySelectorAll(s){return s==='[data-guide-group]'?groups:s==='[data-guide-target]'?buttons:[];}};}
  ids.set('#guideview',element());ids.set('#toc',element());const head=element();
  const c={module:{exports:{}},console,Map,Set,URL,encodeURIComponent,decodeURIComponent,location:{hash:'#/guide'},S:{project:{root:'C:/TEMP/甲',name:'样板项目'}},view:'guide',document:{title:'',head,documentElement:head,createElement:()=>element(),getElementById:id=>ids.get(id)||null},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},window:{addEventListener:(t,fn,capture)=>{(windowEvents[t]??=[]).push({fn,capture});}},history:{pushState(_a,_b,url){c.location.hash=url;},replaceState(_a,_b,url){c.location.hash=url;}},matchMedia:()=>({matches:false}),getLang:()=>c.lang||'zh',esc:s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x])),pathish:()=>false,purl:s=>s,BUST:{},readingFlames:zh=>'FLAMES:'+zh,completeReading:async()=>{},$:s=>ids.get(s),api:async(method,url)=>{calls.push({method,url});assert.equal(method,'GET');return{text:docs[url.endsWith('en')?'en':'zh']};}};
  vm.createContext(c);vm.runInContext(render,c);vm.runInContext(code,c);
  const run=s=>vm.runInContext(s,c),event=dataset=>({target:{dataset,closest(s){if(s==='[data-lang]'&&dataset.lang)return this;if(s==='[data-guide-target]'&&dataset.guideTarget)return this;return null;}},preventDefault(){this.prevented=true;},stopPropagation(){this.stopped=true;}});
  return {c,ids,calls,storage,scrolls,windowEvents,groups,buttons,run,event,ui:c.module.exports.GuideUI};
}
test('every original chapter retains its own stable numeric anchor and source order',()=>{const f=fixture();for(const [lang,count]of [['zh',32],['en',33]]){const m=f.ui.build(docs[lang],lang),old=m.entries.filter(e=>/^g-\d+$/.test(e.id));assert.equal(old.length,count);assert.equal(m.missing.length,0);for(let i=0;i<count;i++){assert.equal(old[i].id,'g-'+i);assert.equal(old[i].label,f.ui.legacy(lang)[i].label);assert.equal((m.body.match(new RegExp('id="g-'+i+'"','g'))||[]).length,1);}}});
test('quickstart is separate and does not consume old h2 indices',()=>{const f=fixture(),source='# Guide\n<!-- guide-quickstart:begin -->\n## New start\n### First step\n<!-- guide-quickstart:end -->\n'+f.ui.legacy('zh').map(e=>'## '+e.label).join('\n'),m=f.ui.build(source,'zh');assert.match(m.quick,/New start/);assert.doesNotMatch(m.body,/New start/);assert.equal(m.entries.filter(e=>/^g-/.test(e.id)).length,32);assert.ok(m.entries.some(e=>e.id==='guide-step-1'));});
test('language mapping follows meaning across the English-only domestic routes chapter',()=>{const f=fixture();assert.equal(f.ui.mapLanguage('g-28','zh','en'),'g-29');assert.equal(f.ui.mapLanguage('g-29','en','zh'),'g-28');assert.equal(f.ui.mapLanguage('g-28','en','zh'),'guide-start');assert.equal(f.ui.mapLanguage('g-31','zh','en'),'g-32');});
test('old title slugs and original fragments resolve without global Markdown changes',()=>{const f=fixture(),m=f.ui.build(docs.zh,'zh');for(const e of f.ui.legacy('zh')){assert.equal(f.ui.find(m,e.id).semantic,e.semantic);assert.equal(f.ui.find(m,f.ui.slug(e.label)).semantic,e.semantic);assert.equal(f.ui.find(m,encodeURIComponent(e.label)).semantic,e.semantic);}assert.equal(f.ui.find(m,f.ui.slug('使用说明')).id,'guide-title');assert.equal(f.ui.find(m,'unknown-section'),null);});
test('repeated headings have unique aliases rather than duplicated HTML ids',()=>{const f=fixture(),m=f.ui.build('# Guide\n## Duplicate\n## Duplicate\n### Duplicate','en'),ids=[...(m.header+m.body).matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(ids.length,new Set(ids).size);assert.ok(m.aliases.has('duplicate'));assert.ok(m.aliases.has('duplicate-1'));});
test('new reading flames h3 remains readable and maps semantically across languages',()=>{const f=fixture(),zh=f.ui.build(docs.zh,'zh'),en=f.ui.build(docs.en,'en');assert.match(zh.body,/三枚读取火苗/);assert.match(en.body,/Three reading flames/);assert.ok(zh.entries.some(e=>e.semantic==='reading-flames'));assert.ok(en.entries.some(e=>e.semantic==='reading-flames'));});
test('local title links stay on the guide route, while fenced and inline code stay literal',()=>{const f=fixture(),m=f.ui.build('# Guide\n## Target\n[Go](#target)\n\n```md\n[No](#target)\n```\n\n`[Literal](#target)`','en');assert.match(m.body,/href="#\/guide\?g=target" data-guide-target="target"/);assert.match(m.body,/<pre[^>]*>\[No\]\(#target\)/);assert.match(m.body,/<code>\[Literal\]\(#target\)<\/code>/);assert.doesNotMatch(m.body,/data-guide-target="javascript/);});
test('directory contains five native folding themes with buttons and fine gold focus',async()=>{const f=fixture();await f.c.module.exports.showGuide();const toc=f.ids.get('#toc').innerHTML;assert.equal((toc.match(/<details\b/g)||[]).length,5);assert.equal((toc.match(/<summary>/g)||[]).length,5);assert.match(toc,/type="button"/);assert.doesNotMatch(toc,/data-to=/);assert.match(f.ids.get('guide-ui-style').textContent,/:focus-visible.*--hover-gold/);assert.equal(f.calls.every(x=>x.method==='GET'),true);});
test('folding preferences are shared by guide languages but isolated by project',()=>{const f=fixture();const state=f.ui.state('A');assert.equal(state.start,true);state.run=true;state.start=false;f.ui.saveState('A',state);assert.equal(f.ui.state('A').run,true);assert.equal(f.ui.state('A').start,false);assert.equal(f.ui.state('B').run,false);});
test('selecting a chapter opens its group, keeps the app route and records a readable selected item',async()=>{const f=fixture();await f.c.module.exports.showGuide();assert.equal(f.c.module.exports.guideNavigate('g-17',true),true);assert.equal(f.c.location.hash,'#/guide?g=g-17');assert.equal(f.groups.find(e=>e.dataset.guideGroup==='run').open,true);assert.ok(f.buttons.find(e=>e.dataset.guideTarget==='g-17').classList.contains('on'));assert.equal(f.scrolls.at(-1).id,'g-17');});
test('switching language uses the selected semantic key rather than the old numeric index',async()=>{const f=fixture();await f.c.module.exports.showGuide();f.c.module.exports.guideNavigate('g-28',true);const click=f.ids.get('#guideview').listeners.click[0];click(f.event({lang:'en'}));await new Promise(setImmediate);assert.equal(f.run('GL'),'en');assert.equal(f.run('GUIDESELECT'),'g-29');assert.equal(f.run('GUIDESEMANTIC'),'resources');});
test('same successful guide refresh retains content DOM and reading selection',async()=>{const f=fixture();await f.c.module.exports.showGuide();f.c.module.exports.guideNavigate('g-19',false);const writes=f.ids.get('#guideview').assignments;await f.c.module.exports.showGuide();assert.equal(f.ids.get('#guideview').assignments,writes);assert.equal(f.run('GUIDESELECT'),'g-19');});
test('same successful refresh with an explicit chapter route preserves the reading position',async()=>{const f=fixture();await f.c.module.exports.showGuide();f.c.module.exports.guideNavigate('g-19',true);const scrolls=f.scrolls.length,writes=f.ids.get('#guideview').assignments;await f.c.module.exports.showGuide();assert.equal(f.scrolls.length,scrolls);assert.equal(f.ids.get('#guideview').assignments,writes);assert.equal(f.run('GUIDESELECT'),'g-19');f.c.location.hash='#/guide?g=g-20';await f.c.module.exports.showGuide();assert.equal(f.scrolls.at(-1).id,'g-20');});
test('an old project response cannot fill the guide after the project changes',async()=>{const f=fixture(),wait=deferred();f.c.api=()=>wait.promise;const pending=f.c.module.exports.showGuide();f.c.S={project:{root:'C:/TEMP/乙',name:'新项目'}};wait.resolve({text:'旧内容'});await pending;assert.doesNotMatch(f.ids.get('#guideview').innerHTML,/旧内容/);});
test('read success waits for the existing flame completion helper and rechecks the project afterwards',async()=>{const f=fixture(),wait=deferred();let completed=0;f.c.completeReading=()=>{completed++;return wait.promise;};const pending=f.c.module.exports.showGuide();await new Promise(setImmediate);assert.equal(completed,1);assert.doesNotMatch(f.ids.get('#guideview').innerHTML,/guide-body/);f.c.S={project:{root:'C:/TEMP/乙',name:'新项目'}};f.ids.get('#guideview').innerHTML='新项目页面';wait.resolve();await pending;assert.equal(f.ids.get('#guideview').innerHTML,'新项目页面');});
test('read errors display immediately and never invoke success flame completion',async()=>{const f=fixture();f.c.api=async()=>{throw Error('读取失败');};f.c.completeReading=()=>{throw Error('Fake completion');};await f.c.module.exports.showGuide();assert.match(f.ids.get('#guideview').innerHTML,/role="alert".*读取失败/);});
test('legacy fragment clicks are normalized only inside the current guide',async()=>{const f=fixture();await f.c.module.exports.showGuide();f.c.location.hash='#目标蓝图';for(const e of f.windowEvents.hashchange)e.fn();assert.equal(f.c.location.hash,'#/guide?g=g-4');f.c.view='skills';f.c.location.hash='#目标蓝图';for(const e of f.windowEvents.hashchange)e.fn();assert.equal(f.c.location.hash,'#目标蓝图');});
test('the preview fixes obsolete Zen and language wording while retaining current workflow and flame guidance',()=>{for(const text of Object.values(docs)){assert.doesNotMatch(text,/正文居中|居中的阅读宽度|the text is centred|Zen keeps its centred reading width/);}assert.match(docs.zh,/- \*\*语言\*\*：语言三档/);assert.match(docs.en,/- \*\*Language\*\*: language/);assert.match(docs.zh,/需要审核的任务必须使用有效的批准计划/);assert.match(docs.en,/Current execution rules:/);assert.match(docs.zh,/### 三枚读取火苗/);assert.match(docs.en,/### Three reading flames/);});

