'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {fixture}=require('./test_pane_spirit.js');
const full=fs.readFileSync(path.resolve(__dirname,'../../模板.html'),'utf8');
function block(begin,end){const a=full.indexOf(begin),b=full.indexOf(end,a);assert.ok(a>=0&&b>a);return full.slice(a,b);}
const motion=block('/* Motion preference:','/* End motion preference. */'),sword=block('/* Business display handle:','/* End business display handle. */');
function setup(reduced=false,stored){const f=fixture(),listeners=new Set();let media={matches:reduced,addEventListener(n,fn){listeners.add(fn);}};if(stored)f.storage.set('tpl_motion',stored);f.window.matchMedia=()=>media;f.window.dispatchEvent=e=>{for(const fn of f.events.get(e.type)||[])fn(e);};const ctx={window:f.window,document:f.document,localStorage:f.window.localStorage,getLang:()=> 'zh',Number,String,Math,Object,console};vm.createContext(ctx);vm.runInContext(motion+sword,ctx);return Object.assign(f,{ctx,media,systemReduce(value){media.matches=value;for(const fn of listeners)fn();}});}
test('motion preference restores, persists and system reduction overrides requested on',()=>{const f=setup(false,'off');try{assert.equal(f.window.MiracleMotion.enabled(),false);assert.equal(f.document.documentElement.getAttribute('data-motion'),'off');f.window.MiracleMotion.set(true);assert.equal(f.storage.get('tpl_motion'),'on');assert.equal(f.window.MiracleMotion.enabled(),true);f.systemReduce(true);assert.equal(f.window.MiracleMotion.requested(),true);assert.equal(f.window.MiracleMotion.enabled(),false);f.systemReduce(false);assert.equal(f.window.MiracleMotion.enabled(),true);assert.equal(f.external.length,0);}finally{f.cleanup();}});
test('motion preference applies even when browser storage throws',()=>{const f=setup();try{f.window.localStorage.setItem=()=>{throw Error('quota');};f.window.MiracleMotion.set(false);assert.equal(f.window.MiracleMotion.enabled(),false);assert.equal(f.document.documentElement.getAttribute('data-motion'),'off');assert.equal(f.external.length,0);}finally{f.cleanup();}});
function handle(f,root){const lane=f.el('div','',f.document.body),h=f.el('span','business-marker',lane);let capture=null;h.setPointerCapture=id=>{capture=id;};h.hasPointerCapture=id=>capture===id;h.releasePointerCapture=()=>{capture=null;};const dispose=f.ctx.bindBusinessNavHandle(lane,h,root);return{lane,h,dispose,captured:()=>capture,event(type,values={}){h.dispatchEvent({type,preventDefault(){},...values});}};}
test('real sword pointer drag clamps scaling, retains project preference and releases capture',()=>{const f=setup();try{const a=handle(f,'C:/test/a');a.event('pointerdown',{button:0,pointerId:5,clientX:500});a.event('pointermove',{pointerId:5,clientX:100});assert.equal(a.lane.style['--business-scale'],'1.6');assert.equal(a.h.getAttribute('aria-valuenow'),'160');assert.equal(a.captured(),5);a.event('pointerup',{pointerId:5});assert.equal(a.captured(),null);assert.equal(a.lane.classList.contains('business-dragging'),false);a.dispose();const b=handle(f,'C:/test/b');assert.equal(b.lane.style['--business-scale'],'1');b.dispose();const again=handle(f,'c:\\test\\a');assert.equal(again.lane.style['--business-scale'],'1.6');again.dispose();assert.equal(f.external.length,0);}finally{f.cleanup();}});
test('sword keys, reset and reduced motion keep the same business DOM without dispatch',()=>{const f=setup(true);try{const a=handle(f,'C:/test/a'),module=f.el('a','module-business',a.lane);a.event('keydown',{key:'ArrowLeft',shiftKey:true});assert.equal(a.lane.style['--business-scale'],'1.1');assert.equal(a.h.classList.contains('business-settle'),false);a.event('keydown',{key:'End'});assert.equal(a.lane.style['--business-scale'],'1.6');a.event('dblclick');assert.equal(a.lane.style['--business-scale'],'1');assert.ok(a.lane.contains(module));a.event('pointerdown',{button:0,pointerId:3,clientX:400});f.window.dispatchEvent({type:'hashchange'});assert.equal(a.captured(),null);a.dispose();a.event('keydown',{key:'End'});assert.equal(a.lane.style['--business-scale'],'1');for(const listeners of a.h.events.values())assert.equal(listeners.size,0);assert.equal(f.external.length,0);}finally{f.cleanup();}});
test('turning motion off while a sword is held ends its decorative state and keeps scale',()=>{const f=setup();try{const a=handle(f,'C:/test/a');a.event('pointerdown',{button:0,pointerId:4,clientX:400});a.event('pointermove',{pointerId:4,clientX:348});assert.equal(a.lane.style['--business-scale'],'1.2');f.window.MiracleMotion.set(false);assert.equal(a.captured(),null);assert.equal(a.lane.style['--business-scale'],'1.2');assert.equal(a.h.classList.contains('business-settle'),false);a.dispose();assert.equal(f.external.length,0);}finally{f.cleanup();}});
test('flame success is immediate when app motion is off, and no animation completion remains',async()=>{const f=setup(false,'off');try{const host=f.el('div','',f.document.body),loading=f.el('span','ps-loading',host);f.el('span','ps-loading-fires',loading);assert.equal(await f.window.PaneSpirit.complete(host),true);assert.ok(loading.classList.contains('ps-loading-complete'));assert.equal((f.events.get('research-motion-change')||new Set()).size,0);assert.equal(f.external.length,0);}finally{f.cleanup();}});
test('changing motion off resolves a real pending flame completion and removes its listener',async()=>{const f=setup();try{let timers=0;f.window.setTimeout=()=>{timers++;return 1;};f.window.clearTimeout=()=>{timers--;};const host=f.el('div','',f.document.body),loading=f.el('span','ps-loading',host);f.el('span','ps-loading-fires',loading);const pending=f.window.PaneSpirit.complete(host);assert.equal(timers,1);assert.equal(f.events.get('research-motion-change').size,1);f.window.MiracleMotion.set(false);assert.equal(await pending,true);assert.equal(timers,0);assert.equal(f.events.get('research-motion-change').size,0);assert.ok(loading.classList.contains('ps-loading-complete'));}finally{f.cleanup();}});
