'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const template=fs.readFileSync(process.env.READER_STICKY_TEMPLATE||path.resolve(__dirname,'../../模板.html'),'utf8').replace(/\r\n/g,'\n');
function fn(name){const match=template.match(new RegExp('(?:async )?function '+name+'\\('));assert.ok(match,'production function '+name);const start=match.index,brace=template.indexOf('{',start);let depth=0,quote='',line=false,block=false;for(let i=brace;i<template.length;i++){const c=template[i],next=template[i+1];if(line){if(c==='\n')line=false;continue;}if(block){if(c==='*'&&next==='/'){block=false;i++;}continue;}if(quote){if(c==='\\'){i++;continue;}if(c===quote)quote='';continue;}if(c==='/'&&next==='/'){line=true;i++;continue;}if(c==='/'&&next==='*'){block=true;i++;continue;}if(c==='"'||c==="'"||c==='`'){quote=c;continue;}if(c==='{')depth++;if(c==='}'&&--depth===0)return template.slice(start,i+1);}assert.fail('unterminated production function '+name);}
function between(start,end){const i=template.indexOf(start),j=template.indexOf(end,i);assert.ok(i>=0&&j>i,start);return template.slice(i,j);}
class Element {
  constructor(doc,tag='div',attrs={}){this.ownerDocument=doc;this.tagName=tag.toUpperCase();this.attrs={...attrs};this.children=[];this.parentNode=null;this.listeners=new Map();this.style={setProperty(k,v){this[k]=v;}};this.dataset={};this.value='';this.scrollTop=0;this.scrollLeft=0;this.clientWidth=900;this.clientHeight=650;this.hidden=Object.hasOwn(attrs,'hidden');this.html='';const classes=new Set((attrs.class||'').split(/\s+/).filter(Boolean));this.classList={add:(...xs)=>xs.forEach(x=>classes.add(x)),remove:(...xs)=>xs.forEach(x=>classes.delete(x)),contains:x=>classes.has(x),toggle:(x,on)=>{const next=on===undefined?!classes.has(x):on;next?classes.add(x):classes.delete(x);return next;}};for(const[k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;}
  get id(){return this.attrs.id||'';}get isConnected(){return this.ownerDocument.body.contains(this);}get parentElement(){return this.parentNode;}
  appendChild(node){assert.ok(node,'appendChild needs a real existing node');if(node.parentNode)node.parentNode.children=node.parentNode.children.filter(x=>x!==node);this.children.push(node);node.parentNode=this;return node;}
  remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(x=>x!==this);this.parentNode=null;}
  contains(node){return node===this||this.children.some(x=>x.contains(node));}
  set innerHTML(html){this.html=html;for(const child of this.children)child.parentNode=null;this.children=[];const stack=[this];for(const token of html.matchAll(/<!--[\s\S]*?-->|<\/?[^>]+>|[^<]+/g)){const text=token[0];if(text.startsWith('<!--'))continue;if(text.startsWith('</')){if(stack.length>1)stack.pop();continue;}if(!text.startsWith('<'))continue;const tag=text.match(/^<([\w-]+)/);if(!tag)continue;const attrs={};for(const a of text.matchAll(/\s([\w-]+)(?:="([^"]*)"|='([^']*)')?/g))attrs[a[1]]=a[2]??a[3]??'';const node=new Element(this.ownerDocument,tag[1],attrs);stack.at(-1).appendChild(node);if(!/^(input|img|br|hr|meta|link)$/i.test(tag[1])&&!text.endsWith('/>'))stack.push(node);}}
  get innerHTML(){return this.html;}set textContent(v){this.text=String(v);}get textContent(){return this.text||'';}
  matches(selector){if(selector.startsWith('#'))return this.id===selector.slice(1);if(selector.startsWith('.'))return selector.slice(1).split('.').every(x=>this.classList.contains(x));const attr=selector.match(/^\[([^=\]]+)(?:="([^"]*)")?\]$/);if(attr)return Object.hasOwn(this.attrs,attr[1])&&(attr[2]===undefined||this.attrs[attr[1]]===attr[2]);return this.tagName.toLowerCase()===selector.toLowerCase();}
  closest(selector){for(let el=this;el;el=el.parentNode)if(selector.split(',').some(s=>el.matches(s.trim())))return el;return null;}
  querySelectorAll(selector){const out=[];const alternatives=selector.split(',').map(s=>s.trim().split(/\s+/));function visit(node){for(const child of node.children){for(const pieces of alternatives){if(!child.matches(pieces.at(-1)))continue;let parent=child.parentNode,i=pieces.length-2;while(parent&&i>=0){if(parent.matches(pieces[i]))i--;parent=parent.parentNode;}if(i<0){out.push(child);break;}}visit(child);}}visit(this);return out;}
  querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
  setAttribute(k,v){this.attrs[k]=String(v);}addEventListener(type,fn){if(!this.listeners.has(type))this.listeners.set(type,[]);this.listeners.get(type).push(fn);}
  async emit(type,target=this,extra={}){for(const listener of this.listeners.get(type)||[])await listener({target,preventDefault(){},stopPropagation(){},...extra});}
  focus(){this.ownerDocument.activeElement=this;}setSelectionRange(a,b){this.selectionStart=a;this.selectionEnd=b;}
  getBoundingClientRect(){return{left:0,top:0,right:900,bottom:650,width:900,height:650};}
  async requestFullscreen(){if(this.ownerDocument.rejectFullscreen)throw Error('native fullscreen unavailable');this.ownerDocument.fullscreenElement=this;await this.ownerDocument.emit('fullscreenchange');}
}
class Document {
  constructor(){this.body=new Element(this,'body');this.documentElement=new Element(this,'html');this.activeElement=null;this.fullscreenElement=null;this.listeners=new Map();}
  getElementById(id){return this.body.id===id?this.body:this.body.querySelector('#'+id);}querySelector(s){return this.body.querySelector(s);}querySelectorAll(s){return this.body.querySelectorAll(s);}
  addEventListener(type,fn){if(!this.listeners.has(type))this.listeners.set(type,[]);this.listeners.get(type).push(fn);}async emit(type){for(const listener of this.listeners.get(type)||[])await listener();}
  async exitFullscreen(){this.fullscreenElement=null;await this.emit('fullscreenchange');}
}
function fixture(parts={'文本':['译文.md'],'图片':[],'图解':[]}) {
  const doc=new Document(),body=doc.body;
  function element(tag,id,parent=body,attrs={}){const n=new Element(doc,tag,{id,...attrs});parent.appendChild(n);return n;}
  const host=element('main','modview'),tree=element('aside','tree'),note=element('aside','note'),ta=element('textarea','nta',note),toastNode=element('div','toast');
  const zenBtn=element('button','zen'),save=element('button','nsave',note),idea=element('button','nidea',note),scope=element('span','nscope',note);
  ta.value='synthetic existing draft';ta.oninput=()=>{calls.push({draft:true,text:ta.value});};const calls=[],alerts=[],memory=new Map();
  const pdf={identity:'unchanged PDF'},x={code:'L7',title:'Synthetic paper',pdf:'原文/L7 Synthetic.pdf',folder:'解读/L7 Synthetic',parts};
  const ctx={document:doc,window:null,$:s=>doc.querySelector(s),cur:'文献',view:'mod',MV:{sel:null},LIBDATA:{items:[x]},READ:'#读:',ACT:{viewed:[]},LASTFILE:{},ZPOS:{},BLUEPRINTMAP:'#map',RULEMAP:'#rules',MODULEMAP:'#module',zenBtn,note,ta,NIMG:[],NUP:0,FRAMING:new Set(),online:true,noteDirty:false,encodeURIComponent,localStorage:{getItem:k=>memory.get(k)||null},act(){},fileHash(){},landOn(){},placeGrip(){},invalidateModuleReading(){},scrollY:0,zkey:(m,p)=>m+'|'+p,esc:s=>String(s),libLoad:async()=>{},rdPdf:async()=>{ctx.RD.pdf=pdf;},rdFollow(){},rdRefit:async()=>{},rdMarks(){},rdPop(){},applyBox(){},loadDrafts(){calls.push({draftRead:true});},reportNote(){calls.push({scope:ctx.noteScope()});},loadFresh(){},showNotes(){},count(){},renderAtt(){},saveNote(v){calls.push({draftRecorded:v});},toast:s=>alerts.push(s),setTimeout(){},zenToc(){},zenDisarm(){},zenPos(){},syncSoon(){},confirm(){return true;},renderMd:text=>'<p>'+text+'</p>',getSelection:()=>({removeAllRanges(){}}),api:async(method,url,data)=>{calls.push({method,url,data});if(method==='GET'&&url.endsWith('/marks'))return{items:[]};if(method==='GET'&&url.includes('/preview?'))return{text:'synthetic history or translation'};if(method==='POST'&&url.endsWith('/marks'))return{id:'批-1',...data};if(method==='POST'&&url.startsWith('api/notes/'))return{id:'文-001',body:data.text};throw Error('unexpected API '+method+' '+url);}};
  ctx.window=ctx;ctx.window.dispatchEvent=()=>{};vm.createContext(ctx);
  const rdState=between('const RD = {','const SVGNS');
  const event=between("document.addEventListener('fullscreenchange', function ()",'\n});')+'\n});';
  const readerClick=between("$('#modview').addEventListener('click', async function (e) {\n  if (!MV.sel || MV.sel.indexOf(READ) !== 0)","$('#modview').addEventListener('keydown'");
  const saveHandler=between("document.getElementById('nsave').onclick = async function ()",'\n};')+'\n};';
  ctx.ICON_NAMES={jade:[],myth:[],classic:[]};ctx.getLang=()=> 'both';ctx.moduleReadRoot=()=> 'synthetic';ctx.location={hash:'#/m/文献'};ctx.readingFlames=()=> 'Reading';
  const script=[rdState,...['builtinFileSlot','builtinLockIcon','stickyNoteIcon','iconSvg','curIconStyle','applyUtilityIcons','pvWrap','overviewNotes','vOpen','vShow','showReader','rdBase','rdReturnFloating','rdSyncFloating','rdStickyNote','rdRight','rdFull','rdFullBtn','rdMark','toggleNote','appendNote','noteScope','recordNote','setZen'].map(fn),event,readerClick,saveHandler,'globalThis.RD=RD;'].join('\n');
  vm.runInContext(script,ctx);return{ctx,doc,host,tree,note,ta,toastNode,save,idea,scope,calls,alerts,pdf,x,open:()=>ctx.showReader('L7'),click:async attr=>{const target=doc.querySelector('['+attr+']');assert.ok(target,attr);await host.emit('click',target);},idle:async()=>{await Promise.resolve();await Promise.resolve();}};
}
test('reader has a visible sticky control while an absent historical note is not invented',async()=>{const f=fixture();await f.open();await f.idle();assert.ok(f.doc.querySelector('#rd .rdtool [data-rdsticky]'));assert.ok(!f.doc.querySelector('[data-rdfile="笔记.md"]'));assert.ok(!f.doc.querySelector('#rdNew'));assert.ok(f.calls.filter(c=>c.method).every(c=>c.method==='GET'));});
test('page cite opens the same global sticky draft with the current source, without a library-note write',async()=>{const f=fixture();await f.open();const before=f.ta.value;f.doc.getElementById('cite').onclick();assert.equal(f.doc.getElementById('note'),f.note);assert.ok(f.note.classList.contains('open'));assert.ok(f.ta.value.startsWith(before));assert.match(f.ta.value,/L7 · Synthetic paper/);assert.match(f.ta.value,/资料\/文献\/原文\/L7 Synthetic\.pdf/);assert.equal(f.doc.activeElement,f.ta);const draft=f.ta.value;f.doc.getElementById('cite').onclick();assert.equal(f.ta.value,draft);assert.ok(!f.calls.some(c=>c.method==='POST'));assert.equal(f.ctx.RD.pdf,f.pdf);});
test('Zen and the reader sticky button keep the existing paper, sticky node and draft',async()=>{const f=fixture();await f.open();f.ctx.setZen(true);const before=f.ta.value,rd=f.doc.getElementById('rd');await f.click('data-rdsticky');assert.ok(f.doc.body.classList.contains('zen'));assert.equal(f.doc.getElementById('rd'),rd);assert.equal(f.ctx.RD.pdf,f.pdf);assert.equal(f.doc.getElementById('note'),f.note);assert.ok(f.ta.value.startsWith(before));});
test('native fullscreen contains the original sticky, whose reader control can reopen it',async()=>{const f=fixture();await f.open();const rd=f.doc.getElementById('rd'),before=f.ta.value;await f.ctx.rdFull();assert.equal(f.doc.fullscreenElement,rd);assert.ok(rd.contains(f.note)&&rd.contains(f.toastNode));assert.ok(rd.contains(f.doc.querySelector('[data-rdsticky]')));await f.click('data-rdsticky');assert.ok(f.note.classList.contains('open'));assert.ok(f.ta.value.startsWith(before));assert.equal(f.doc.activeElement,f.ta);await f.doc.exitFullscreen();assert.equal(f.note.parentNode,f.doc.body);assert.equal(f.toastNode.parentNode,f.doc.body);});
test('fallback fullscreen opens the same sticky without requesting a new paper or replacing its draft',async()=>{const f=fixture();await f.open();f.doc.rejectFullscreen=true;const paperCalls=f.calls.filter(c=>c.method).length;await f.ctx.rdFull();assert.ok(f.doc.getElementById('rd').classList.contains('rdfs'));await f.click('data-rdsticky');assert.equal(f.doc.fullscreenElement,null);assert.equal(f.note.parentNode,f.doc.body);assert.ok(f.note.classList.contains('open'));assert.equal(f.ctx.RD.pdf,f.pdf);assert.equal(f.calls.filter(c=>c.method).length,paperCalls);});
test('reader replacement and fullscreen exit keep original sticky and toast connected',async()=>{const f=fixture();await f.open();await f.ctx.rdFull();f.note.classList.add('open');const before=f.ta.value,old=f.doc.getElementById('rd');await f.open();assert.notEqual(f.doc.getElementById('rd'),old);assert.ok(!old.isConnected);assert.equal(f.doc.getElementById('note'),f.note);assert.equal(f.doc.getElementById('toast'),f.toastNode);assert.equal(f.note.parentNode,f.doc.body);await f.doc.exitFullscreen();assert.equal(f.ctx.overviewNotes(),f.note);assert.equal(f.ta.value,before);assert.equal(f.doc.activeElement,f.ta);});
test('an overview early-return replacement also returns existing floating nodes before clearing',async()=>{const f=fixture();await f.open();await f.ctx.rdFull();f.ctx.MV.sel='#map';assert.equal(f.ctx.vShow('文献','#map','synthetic map','<div>map</div>'),true);assert.equal(f.doc.getElementById('note'),f.note);assert.equal(f.doc.getElementById('toast'),f.toastNode);await f.doc.exitFullscreen();assert.equal(f.note.parentNode,f.doc.body);});
test('an existing historical note remains a normal read-only preview rather than a special editor',async()=>{const f=fixture({'文本':['笔记.md'],'图片':[],'图解':[]});await f.open();await f.idle();assert.ok(f.doc.querySelector('[data-rdfile="笔记.md"]'));assert.match(f.doc.getElementById('rdBody').innerHTML,/synthetic history/);assert.ok(!f.doc.querySelector('#rdNew'));assert.ok(!f.doc.querySelector('[data-rdnedit]'));assert.ok(f.calls.some(c=>c.url&&c.url.includes('/preview?')&&decodeURIComponent(c.url).endsWith('/文本/笔记.md')));assert.ok(!f.calls.some(c=>c.url&&/\/notes(?:$|\/)|\/note$/.test(c.url)));});
test('selected text enters the same sticky draft and saves through the existing unified notebook API',async()=>{const f=fixture();await f.open();f.ctx.RD.sel={page:3,quote:'synthetic quoted sentence',rects:[]};const target=new Element(f.doc,'button',{'data-rdnote':''});f.doc.getElementById('rd').appendChild(target);await f.host.emit('click',target);assert.match(f.ta.value,/第 3 页/);assert.match(f.ta.value,/> synthetic quoted sentence/);assert.ok(!f.calls.some(c=>c.method==='POST'));await f.save.onclick();const writes=f.calls.filter(c=>c.method==='POST');assert.equal(writes.length,1);assert.equal(writes[0].url,'api/notes/'+encodeURIComponent('文献'));assert.match(writes[0].data.text,/synthetic quoted sentence/);assert.equal(f.ta.value,'');assert.ok(!writes.some(c=>c.url.startsWith('api/library/')));});
test('PDF annotations keep their marks API but no longer create a dedicated notebook entry',async()=>{const f=fixture();await f.open();f.ctx.RD.stk={page:2,at:[40,50]};const input=new Element(f.doc,'input',{id:'rdStk'});input.value='synthetic PDF annotation';f.doc.getElementById('rd').appendChild(input);const button=new Element(f.doc,'button',{'data-rdstksave':''});f.doc.getElementById('rd').appendChild(button);await f.host.emit('click',button);const writes=f.calls.filter(c=>c.method==='POST');assert.equal(writes.length,1);assert.match(writes[0].url,/\/marks$/);assert.equal(writes[0].data.text,input.value);assert.equal(f.ctx.RD.marks.length,1);assert.ok(!writes.some(c=>/\/note$/.test(c.url)));});

test('reader and preview fullscreen shortcuts use the existing quill sprite in every icon style',async()=>{for(const style of ['jade','myth','classic']){const f=fixture();f.ctx.localStorage.getItem=k=>k==='tpl_nav_icon_style'?style:null;await f.open();for(const button of [f.doc.getElementById('cite'),f.doc.querySelector('[data-rdsticky]')]){assert.match(button.querySelector('use').attrs.href,/\.svg#quillnote$/);assert.equal(button.attrs['aria-label'],'便签 Sticky note');assert.equal(button.attrs.title,'便签 Sticky note');}const preview=new Element(f.doc);preview.innerHTML=f.ctx.pvWrap('<p>synthetic preview</p>','synthetic file');const button=preview.querySelector('[data-pvnote]');assert.match(button.querySelector('use').attrs.href,/\.svg#quillnote$/);assert.equal(button.attrs['aria-label'],'便签 Sticky note');assert.match(button.attrs.title,/N/);}});

test('global shortcut retains its badge and quill in classic text mode while left notebook navigation keeps its mapping',()=>{const f=fixture(),button=new Element(f.doc,'button',{id:'notebtn'}),badge=new Element(f.doc,'span',{id:'nbadge'}),left=new Element(f.doc,'a',{id:'notesTab'});f.doc.body.appendChild(button);button.appendChild(badge);f.doc.body.appendChild(left);const navCalls=[];f.ctx.setNavIcon=(a,icon,zh,en,style)=>navCalls.push({id:a.id,icon,zh,en,style});vm.runInContext(between('const NAV_SPECS=','let ICON_TUNE=')+'\n'+fn('applyNavStyle'),f.ctx);for(const style of ['jade','myth','classic']){f.ctx.localStorage.getItem=()=>style;f.ctx.applyNavStyle();assert.match(button.querySelector('use').attrs.href,/\.svg#quillnote$/);assert.equal(button.querySelector('#nbadge'),badge);assert.ok(button.classList.contains('utility-icon'));assert.equal(button.attrs['aria-label'],'便签 · Sticky note');const mapping=navCalls.filter(x=>x.id==='notesTab').at(-1);assert.equal(mapping.icon,style==='classic'?'':'books');assert.equal(mapping.zh,'笔记本');assert.equal(mapping.en,'Notebook');}assert.ok(!f.calls.some(c=>c.method==='POST'));});

test('PDF annotation keeps its historical tool identity but has a distinct visible label from the global sticky',async()=>{const f=fixture();await f.open();const annotation=f.doc.querySelector('[data-rdtool="便签"]');assert.ok(annotation);assert.match(f.host.innerHTML,/data-rdtool="便签">贴纸/);assert.ok(f.doc.querySelector('[data-rdsticky]'));});

function componentText(name){return fs.readFileSync(path.resolve(__dirname,'../../'+name),'utf8').replace(/\r\n/g,'\n');}
function sliceOf(source,start,end){const a=source.indexOf(start),b=source.indexOf(end,a);assert.ok(a>=0&&b>a,'production component markup '+start);return source.slice(a,b);}
test('map, automation and workflow toolbar rendering keeps a quill across refresh and accepts old helpers without icons',()=>{const f=fixture(),glyph=f.ctx.stickyNoteIcon(),label=x=>x.join(' · '),modes=[true,false];for(const icons of modes){const host=new Element(f.doc),help={notes(){},lang:()=> 'both',...(icons?{notesIcon:()=>glyph}:{})},ctx={host,el:host,help,opts:help,css:'',MODES:[],words:{},esc:String,str:String,label,title:()=>['Synthetic','Synthetic'],thisValue:{host,h:help,uid:'synthetic',motion:true,fs:false,label:(...x)=>x.join(' · ')}};vm.createContext(ctx);
    const gov=componentText('治理界面.js');vm.runInContext(sliceOf(gov,'host.innerHTML=\'<section class="gmap"','\n    const component='),ctx);let button=host.querySelector('[data-gmap-notes]');assert.ok(button);assert.equal(button.querySelector('use')!==null,icons);const update=gov.split('\n').find(x=>x.includes('const notesButton=host.querySelector'));vm.runInContext('{'+update+'}',ctx);vm.runInContext('{'+update+'}',ctx);button=host.querySelector('[data-gmap-notes]');assert.equal(button.querySelector('use')!==null,icons);assert.equal(button.hidden,false);assert.equal(button.attrs['aria-label'],'便签 Sticky note');
    const cm=componentText('代码地图.js');vm.runInContext(sliceOf(cm,'el.innerHTML = \'<div class="cmx-bar"','\n    const stage ='),ctx);button=host.querySelector('[data-act="notes"]');assert.equal(button.querySelector('use')!==null,icons);assert.equal(button.attrs['aria-label'],'便签 Sticky note');
    const auto=componentText('自动化面板.js');vm.runInContext('(function(){'+sliceOf(auto,'const graphControls=','\n    this.click =')+'}).call(thisValue)',ctx);const autoButtons=host.querySelectorAll('[data-ad="notes"]');assert.equal(autoButtons.length,3);for(button of autoButtons){assert.equal(button.querySelector('use')!==null,icons);assert.equal(button.attrs['aria-label'],'便签 Sticky note');}
    const aag=componentText('员工分配图.js');vm.runInContext('(function(){'+sliceOf(aag,'this.host.innerHTML=','\n    this.panel=')+'}).call(thisValue)',ctx);const labels=aag.split('\n').find(x=>x.includes('const labels=')&&x.includes("notes:['便签'"));vm.runInContext('(function(){'+labels+'}).call(thisValue)',ctx);vm.runInContext('(function(){'+labels+'}).call(thisValue)',ctx);button=host.querySelector('[data-aag="notes"]');assert.equal(button.querySelector('use')!==null,icons);assert.equal(button.attrs['aria-label'],'便签 Sticky note');
    const wfe=componentText('流程编辑器.js');vm.runInContext('(function(){'+sliceOf(wfe,'host.innerHTML=','\n    this.panel=')+'}).call(thisValue)',ctx);ctx.thisValue.busy=false;ctx.thisValue.loading=false;ctx.thisValue.active=null;ctx.thisValue.draft={};const refresh=sliceOf(wfe,'const labels=','\n    this.host.querySelector(\'[data-wfe="control"]\')');ctx.active=null;ctx.b=false;vm.runInContext('(function(){'+refresh+'}).call(thisValue)',ctx);vm.runInContext('(function(){'+refresh+'}).call(thisValue)',ctx);button=host.querySelector('[data-wfe="notes"]');assert.equal(button.querySelector('use')!==null,icons);assert.equal(button.attrs['aria-label'],'便签 Sticky note');
  }});
