'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const production=process.env.MH_WORK_PACKAGE_TEMPLATE||path.join(__dirname,'../../模板.html');
const template=fs.readFileSync(production,'utf8');
const staged=!!process.env.MH_WORK_PACKAGE_UI_SOURCE;
const full=staged?fs.readFileSync(process.env.MH_WORK_PACKAGE_UI_SOURCE,'utf8'):template;
function extract(text,begin,end){const a=text.indexOf(begin),b=text.indexOf(end,a);assert.ok(a>=0&&b>a,'Missing production source block: '+begin);return text.slice(a,b);}
const code=extract(template,'function failReading(','/* ================= 首次项目读取 Initial project loading ================= */')+'\n'+extract(template,'/* ================= 模块读取事务 Module loading ================= */','/* ================= 模块读取事务 Module loading 结束 ================= */')+'\n'+extract(full,'/* ================= 编程工作台 Work package UI ================= */','/* ================= 编程工作台 Work package UI 结束 ================= */');
function wait(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
function unescape(s){return String(s).replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');}
class Element{
  constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.parentNode=null;this.dataset={};this.attributes={};this.value='';this.disabled=false;this.checked=false;this.open=false;this.writes=0;this.events={};this._html='';this.textContent='';this.scrollTop=0;const cs=new Set();this.classList={add:(...x)=>x.forEach(k=>cs.add(k)),remove:(...x)=>x.forEach(k=>cs.delete(k)),contains:x=>cs.has(x),toggle:(x,y)=>{const yes=y===undefined?!cs.has(x):!!y;if(yes)cs.add(x);else cs.delete(x);return yes;}};}
  get isConnected(){let n=this;while(n){if(n.tagName==='BODY')return true;n=n.parentNode;}return false;}
  get innerHTML(){return this._html;}
  set innerHTML(html){this._html=String(html);++this.writes;this.children.forEach(n=>n.parentNode=null);this.children=[];const stack=[this];for(const m of String(html).matchAll(/<\/?[A-Za-z][^>]*>/g)){const raw=m[0];if(raw.startsWith('</')){if(stack.length>1)stack.pop();continue;}const tag=raw.match(/^<([A-Za-z0-9]+)/)[1],node=new Element(tag);for(const a of raw.matchAll(/([\w-]+)(?:="([^"]*)")?/g)){if(a.index===1)continue;node.setAttribute(a[1],unescape(a[2]||''));}stack.at(-1).appendChild(node);if(!/^(input|br|hr|img|meta|link)$/i.test(tag))stack.push(node);}}
  appendChild(n){if(n.parentNode)n.remove();n.parentNode=this;this.children.push(n);return n;}
  remove(){if(this.parentNode){this.parentNode.children.splice(this.parentNode.children.indexOf(this),1);this.parentNode=null;}}
  setAttribute(k,v){this.attributes[k]=String(v);if(k==='id')this.id=v;if(k==='class')String(v).split(/\s+/).forEach(c=>this.classList.add(c));if(k==='value')this.value=v;if(['checked','disabled','open'].includes(k))this[k]=true;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;}
  contains(n){return this===n||this.children.some(c=>c.contains(n));}
  matches(s){if(s[0]==='#')return this.id===s.slice(1);if(s[0]==='.')return this.classList.contains(s.slice(1));const a=s.match(/^\[([^\]=]+)(?:="([^\"]*)")?\]$/);if(a)return a[2]===undefined?Object.hasOwn(this.attributes,a[1]):this.attributes[a[1]]===a[2];return this.tagName.toLowerCase()===s;}
  querySelectorAll(s){const xs=[];const walk=n=>n.children.forEach(c=>{if(c.matches(s))xs.push(c);walk(c);});walk(this);return xs;}
  querySelector(s){return this.querySelectorAll(s)[0]||null;}
  closest(s){let n=this;while(n){if(n.matches(s))return n;n=n.parentNode;}return null;}
  addEventListener(type,fn){(this.events[type]||(this.events[type]=[])).push(fn);}
  dispatch(type,target=this){for(const fn of this.events[type]||[])fn({target});}
  scrollIntoView(){this.scrolled=true;}
}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const root='C:/Synthetic/Alpha';
function fixture(goal='S1-1',sub='S2-1',extra={}){const source='治理/目标/'+goal+' 真来源.md';const doc=(text,kind='rule')=>({ref:{kind,scope:goal,source,code:sub,revision:'abc'},reference_state:'ok',document:{source,revision:'abc',state:'ok',complete:true,text_loaded:true,text}});return{
  schema:1,read_only:true,project:{root},request:{goal,sub},task:{what:'作者原话 <script>bad()</script>',how:'真实验收',col:'待你验收',...doc('任务完整原文','task')},goals:[{code:goal,name:'真实目标',...doc('目标全文','goal')}],requirements:[{key:'甲::需-1',func:'需求甲',...doc('甲需求全文','requirement')},{key:'乙::需-1',func:'需求乙',...doc('乙需求全文','requirement')}],
  execution_plans:[{code:'施-1',state:'审核通过',display_state:'失效',valid:false,invalid_reason:'正式计划版本变化',...doc('施工记录')}],selected_plan:null,allowed_files:[],rules:[{layer:'通用',title:'规则',...doc('规则完整原文')}],skills:[{id:'business:novel/unique',title:'小说技能',business:'novel',language:'zh-CN',executed:false,execution_state:'未运行',...doc('技能完整原文','skill')}],context_files:[{approved_path:'backend/example.py',origin:'current_project',content_loaded:false,ref:{source:'backend/example.py',revision:'srcver'},reference_state:'ok',document:{source:'backend/example.py',state:'ok',revision:'srcver',text_loaded:false}}],workorders:[],deliveries:[{code:'J1',state:'待你验收',...doc('交付原文','delivery')}],timeline:[{at:'2026-10-05',time_known:true,who:'G1',what:'保存计划',detail:'P1'},{at:'',time_known:false,what:'记录但时间不明',detail:'未知'}],views:{business:[{business:'novel',skill_id:'business:novel/unique'}]},readiness:{state:'incomplete',plan_valid:false,context_complete:false,execution_authorized:false,gaps:['没有当前有效计划'],warnings:['未读取本机 Git']},snapshot:{digest:'digest-a',consistent:true,generated_at:'2026-10-05T10:00:00',sources:[{source,revision:'abc',state:'ok'},{source:'sqlite:abc',revision:'indexver',state:'ok'}]},prompt:'SERVER PROMPT\n原话，不能客户端重组。',...extra};}
const catalog={items:[{id:'business:novel/unique',kind:'skill',available:true,name:'小说正本',business:'novel'},{id:'link:upstream',kind:'link',name:'不许加入'}, {id:'blocked',kind:'skill',available:false}, {id:'business:novel/unique',kind:'skill'}]};
function harness(){
  const e={requests:[],completed:[],completionWaits:[],toasts:[],copies:[],opened:[],hold:false,body:new Element('body')};e.mv=new Element();e.mv.id='modview';e.tree=new Element();e.tree.id='tree';e.body.appendChild(e.tree);e.body.appendChild(e.mv);
  const ctx={console,Set,WeakMap,JSON,Promise,URLSearchParams,encodeURIComponent,decodeURIComponent,S:{project:{root,name:'Alpha'},blueprint:[{code:'S1-1',name:'目标甲',file:'甲.md',subs:[{code:'S2-1',what:'任务甲',how:'验甲',text:'待你验收'}]},{code:'S1-2',name:'目标乙',file:'乙.md',subs:[{code:'S2-1',what:'任务乙',how:'验乙',text:'没做'}]}]},cur:'源代码',view:'mod',MV:{name:'源代码',sel:null,shown:null,tree:null},PCACHE:{},CMAPCTL:null,LASTFILE:{},CODEMAP:'#代码地图',location:{hash:'#/m/源代码'},
    $:s=>e.body.querySelector(s),esc:escape,getLang:()=>e.lang||'zh',document:{createElement:t=>new Element(t)},navigator:{clipboard:{writeText:async s=>{e.copies.push(s);if(e.copyReject)throw Error('Clipboard denied');}}},
    readingFlames:(zh,en)=>'<span>'+(e.lang==='en'?en:zh)+'</span>',completeReading:async status=>{assert.ok(status.isConnected);e.completed.push(status);if(e.hold){const w=wait();e.completionWaits.push(w);await w.promise;}},toast:s=>e.toasts.push(String(s)),
    api:(method,url)=>{assert.equal(method,'GET');assert.ok(url==='api/skills/catalog'||url.startsWith('api/work-package?'),'Only approved read-only API');const w=wait();e.requests.push({method,url,...w});return w.promise;},
    fileHash:p=>ctx.location.hash='#/m/源代码?f='+encodeURIComponent(p),vOpen:p=>{ctx.invalidateModuleReading();ctx.MV.sel=p;return ctx.cur;},vShow:(name,p,title,html)=>{if(ctx.cur!==name||ctx.MV.sel!==p)return false;e.mv.innerHTML=html;return true;},landOn:(name,p)=>ctx.MV.shown=p,openItem:p=>{ctx.invalidateModuleReading();ctx.MV.sel=p;e.opened.push(p);}};
  ctx.window=ctx;vm.createContext(ctx);vm.runInContext(code,ctx,{filename:production});e.ctx=ctx;e.eval=s=>vm.runInContext(s,ctx);e.state=()=>e.eval('WPK');e.call=(name,...args)=>ctx[name](...args);e.node=s=>e.mv.querySelector(s);e.leave=()=>{ctx.invalidateModuleReading();ctx.view='settings';};e.changeRoot=()=>{ctx.S={...ctx.S,project:{root:'C:/Synthetic/Beta',name:'Beta'}};ctx.moduleReadProjectChanged();ctx.wpkProjectChanged();};return e;
}
const tick=()=>new Promise(a=>setImmediate(a));async function until(fn){for(let i=0;i<30&&!fn();i++)await tick();assert.ok(fn(),'Expected awaited production operation');}
async function finish(e,p=fixture(),cat=catalog){const call=e.call('showWorkPackage');const req=e.requests.at(-2);assert.match(req.url,/api\/work-package/);req.resolve(p);e.requests.at(-1).resolve(cat);await call;return call;}

test('production source exposes only virtual entry and approved pure GET endpoints',()=>{assert.match(code,/const WORKBENCH='#编程工作台'/);assert.doesNotMatch(code,/api\/board|next_task|next_action|api\/auto\/launch|api\/skills\/.*install|api\('POST'/);assert.doesNotMatch(code,/<iframe|CodeMap\.mount|fetch\(/);});
test('task index keeps full goal/sub identities from actual blueprint, including repeated S2 numbers',()=>{const e=harness(),index=e.call('wpkTaskIndex');assert.equal(index.length,2);assert.notEqual(index[0].key,index[1].key);assert.equal(index[1].goal,'S1-2');});
test('empty blueprint shows a truthful empty state without API requests or false readiness',async()=>{const e=harness();e.ctx.S.blueprint=[];await e.call('showWorkPackage');assert.equal(e.requests.length,0);assert.match(e.node('[data-wpk-package]').innerHTML,/暂无任务/);assert.equal(e.node('[data-wpk-copy]').disabled,true);assert.equal(e.completed.length,0);});
test('real success waits for completion, keeps live shell/search, then commits complete originals and source versions',async()=>{const e=harness();e.hold=true;const call=e.call('showWorkPackage'),input=e.node('[data-wpk-search]'),body=e.node('[data-wpk-package]');input.value='unsaved search';e.requests[0].resolve(fixture());e.requests[1].resolve(catalog);await until(()=>e.completionWaits.length===1);assert.equal(e.state().package,null);assert.equal(e.node('[data-wpk-search]'),input);assert.equal(input.value,'unsaved search');assert.doesNotMatch(body.innerHTML,/规则完整原文/);e.completionWaits[0].resolve();const result=await call;assert.equal(result.ok,true);assert.equal(result.scope,'work-package');assert.equal(result.mediaReady,false);for(const s of ['甲需求全文','乙需求全文','规则完整原文','技能完整原文','srcver','待你验收','失效','正式计划版本变化'])assert.ok(body.innerHTML.includes(s),s);assert.ok(body.innerHTML.includes('&lt;script&gt;'));assert.doesNotMatch(body.innerHTML,/<script>/);assert.equal(e.node('[data-wpk-search]'),input);});
test('copy uses the exact server prompt and no additional API/dispatch/launch',async()=>{const e=harness();await finish(e);const count=e.requests.length;assert.equal(await e.call('wpkCopy'),true);assert.equal(e.copies[0],fixture().prompt);assert.equal(e.requests.length,count);assert.equal(e.opened.length,0);});
test('clipboard rejection is reported without marking work done or changing records',async()=>{const e=harness();await finish(e);e.copyReject=true;assert.equal(await e.call('wpkCopy'),false);assert.match(e.toasts.at(-1),/复制失败/);assert.equal(e.state().package.task.col,'待你验收');assert.equal(e.requests.length,2);});
test('same package refresh preserves shell, original details, scroll, task search and skill controls',async()=>{const e=harness();await finish(e);const article=e.node('[data-wpk-package]'),input=e.node('[data-wpk-search]'),skills=e.node('[data-wpk-skills]'),index=e.node('[data-wpk-index]');article.scrollTop=321;input.value='typing';const writes=[article.writes,skills.writes,index.writes];const call=e.call('showWorkPackage');e.requests.at(-1).resolve(fixture());await call;assert.equal(e.node('[data-wpk-package]'),article);assert.equal(article.scrollTop,321);assert.equal(e.node('[data-wpk-search]'),input);assert.equal(input.value,'typing');assert.deepEqual([article.writes,skills.writes,index.writes],writes);assert.equal(e.requests.length,3);});
test('A→B→A late success and catch cannot overwrite the newest selected full task',async()=>{const e=harness(),a=e.call('showWorkPackage');e.eval('WPK.selected=JSON.stringify(["S1-2","S2-1"])');const b=e.call('showWorkPackage');e.eval('WPK.selected=JSON.stringify(["S1-1","S2-1"])');const a2=e.call('showWorkPackage');e.requests[4].resolve(fixture('S1-1','S2-1',{prompt:'LATEST'}));e.requests[5].resolve(catalog);await a2;e.requests[0].resolve(fixture('S1-1','S2-1',{prompt:'OLD'}));e.requests[1].resolve(catalog);e.requests[2].reject(Error('Late B'));e.requests[3].resolve(catalog);await Promise.all([a,b]);assert.equal(e.state().package.prompt,'LATEST');assert.equal(e.completed.length,1);assert.equal(e.toasts.length,0);});
test('root, view, path, serial and host changes during awaited completion suppress old results',async()=>{for(const change of ['root','view','path','serial','host']){const e=harness();e.hold=true;const call=e.call('showWorkPackage');e.requests[0].resolve(fixture());e.requests[1].resolve(catalog);await until(()=>e.completionWaits.length===1);if(change==='root')e.changeRoot();else if(change==='view')e.leave();else if(change==='path')e.ctx.MV.sel='#代码清单';else if(change==='serial')e.eval('++WPK.serial');else{e.mv.remove();e.mv=new Element();e.mv.id='modview';e.body.appendChild(e.mv);}e.completionWaits[0].resolve();await call;assert.equal(e.state().package,null,change);assert.equal(e.toasts.length,0,change);}});
test('project mismatch and task mismatch are rejected before completion without copying old package',async()=>{for(const change of ['project','task']){const e=harness(),call=e.call('showWorkPackage');const p=fixture();if(change==='project')p.project.root='C:/Synthetic/Other';else p.request.goal='S1-2';e.requests[0].resolve(p);e.requests[1].resolve(catalog);const result=await call;assert.equal(result.ok,false);assert.equal(e.completed.length,0);assert.equal(e.state().package,null);assert.equal(await e.call('wpkCopy'),false);assert.match(e.toasts[0],/不一致/);}});
test('late errors after leaving remain silent; current errors retain old readable content and block copy',async()=>{const e=harness();await finish(e);const old=e.node('[data-wpk-package]').innerHTML,call=e.call('showWorkPackage');e.requests.at(-1).reject(Error('<current failure>'));await call;assert.equal(e.node('[data-wpk-package]').innerHTML,old);assert.equal(await e.call('wpkCopy'),false);assert.match(e.mv.children.at(-1).innerHTML,/&lt;current failure&gt;/);const x=harness(),pending=x.call('showWorkPackage');x.leave();x.requests[0].reject(Error('silent'));x.requests[1].resolve(catalog);await pending;assert.equal(x.toasts.length,0);});
test('skill catalog accepts canonical original IDs only; selector deduplicates and excludes link-only',async()=>{const e=harness();await finish(e);const rows=e.call('wpkCatalogItems',catalog);assert.equal(rows.length,1);assert.equal(rows[0].id,'business:novel/unique');assert.doesNotMatch(e.node('[data-wpk-skills]').innerHTML,/link:upstream|blocked/);});
test('actual request repeats plural skill_ids and preserves plan code, full task and chosen language',()=>{const e=harness();e.call('wpkProjectChanged');e.eval('WPK.plan="施-23";WPK.lang="en";WPK.skillIds=["业务:甲/同名","业务:乙/同名"]');const url=e.call('wpkRequestUrl',{goal:'S1-2',sub:'S2-1'}),q=new URLSearchParams(url.split('?')[1]);assert.equal(q.get('plan_code'),'施-23');assert.equal(q.get('lang'),'en');assert.equal(q.get('goal'),'S1-2');assert.deepEqual(q.getAll('skill_ids'),['业务:甲/同名','业务:乙/同名']);assert.equal(q.has('skill_id'),false);});
test('50-skill limit rejects the 51st click and unknown IDs without requesting work or installation',async()=>{const e=harness();const cat={items:Array.from({length:51},(_,i)=>({id:'canonical:'+i,kind:'skill',available:true,name:'Skill '+i}))};await finish(e,fixture(),cat);e.eval('WPK.skillIds=Array.from({length:50},(_,i)=>"canonical:"+i)');const box=e.node('[data-wpk-skills]').querySelectorAll('[data-wpk-skill]')[50];box.checked=true;e.state().host.dispatch('change',box);assert.equal(e.state().skillIds.length,50);assert.equal(box.checked,false);assert.equal(e.requests.length,2);assert.match(e.toasts.at(-1),/50/);});
test('structure/time/business only use actual task membership, saved dates and selected skill businesses',async()=>{const e=harness();await finish(e);e.eval('WPK.mode="time"');const time=e.call('wpkViewHtml');assert.match(time,/2026-10-05/);assert.match(time,/时间未知/);assert.doesNotMatch(time,/undefined/);e.eval('WPK.mode="business"');assert.match(e.call('wpkViewHtml'),/novel/);e.eval('WPK.mode="structure";WPK.query="目标乙"');const structure=e.call('wpkViewHtml');assert.match(structure,/任务乙/);assert.doesNotMatch(structure,/任务甲/);assert.equal(e.requests.length,2);});
test('source paths reject remote, root-outside, traversal, Windows aliases and encoded escapes; Unicode/encoded module filenames stay readable',()=>{const e=harness();for(const bad of ['https://evil.test/x','C:/private.txt','../private','a/../b','//server/share','a\\b','a//b','a/./b','a/%2e%2e/b','a/%252e%252e/b','a%2fb','CON.txt','file.','a /b','a\u0000b'])assert.equal(e.call('wpkPfile',bad),'',bad);assert.equal(e.call('wpkPfile','治理/需求/%E7%BC%96%E7%A0%81.md'),'pfiles/'+['治理','需求','%E7%BC%96%E7%A0%81.md'].map(encodeURIComponent).join('/'));assert.match(e.call('wpkPfile','治理/目标/S1-1 中文.md'),/^pfiles\//);const unsafe=e.call('wpkReference',{ref:{source:'https://evil/x',revision:'x'},document:null});assert.doesNotMatch(unsafe,/href=/);});
test('safe sources are explicit pfiles links only and SQLite versions remain text',async()=>{const e=harness();await finish(e);const html=e.node('[data-wpk-package]').innerHTML;assert.match(html,/href="pfiles\//);assert.match(html,/rel="noopener noreferrer"/);assert.match(html,/sqlite:abc/);assert.doesNotMatch(html,/href="[^\"]*sqlite/);assert.equal(e.opened.length,0);});
test('open source and original records require explicit buttons, keep existing code map link and never start an agent',async()=>{const e=harness();await finish(e);const host=e.state().host,records=e.node('[data-wpk-records]');host.dispatch('click',e.node('[data-wpk-record-button]'));assert.equal(records.open,true);assert.equal(records.scrolled,true);assert.equal(e.opened.length,0);host.dispatch('click',e.node('[data-wpk-source]'));assert.deepEqual(e.opened,['#代码地图']);assert.equal(e.requests.length,2);});
test('root switch clears task, selected skills, chosen plan, cached catalog and copied package',async()=>{const e=harness();await finish(e);e.eval('WPK.skillIds=["business:novel/unique"];WPK.plan="施-1"');e.changeRoot();assert.equal(e.state().package,null);assert.equal(e.state().selected,'');assert.equal(e.state().catalog,null);assert.equal(e.state().skillIds.length,0);assert.equal(e.state().plan,'');assert.equal(await e.call('wpkCopy'),false);});
test('catalog failure reports the actual issue but can deliver the honest task package without installing skills',async()=>{const e=harness(),call=e.call('showWorkPackage');e.requests[0].resolve(fixture());e.requests[1].reject(Error('Catalog unavailable'));const r=await call;assert.equal(r.ok,true);assert.match(e.node('[data-wpk-catalog-error]').textContent,/Catalog unavailable/);assert.equal(e.state().catalog,null);assert.equal(e.requests.length,2);});
test('English keeps task source originals, unknown dates and blocked plans explicit',async()=>{const e=harness();e.lang='en';await finish(e);const html=e.node('[data-wpk-package]').innerHTML;assert.match(html,/Full task source/);assert.match(html,/No currently valid approved plan/);assert.match(html,/Not run/);assert.match(html,/任务完整原文/);assert.match(e.mv.innerHTML,/Structure/);});
test('pending changed plan or skill language cannot copy the previous task instruction',async()=>{const e=harness();await finish(e);e.eval('WPK.plan="施-2";WPK.lang="en"');const call=e.call('showWorkPackage');assert.equal(await e.call('wpkCopy'),false);const q=new URLSearchParams(e.requests.at(-1).url.split('?')[1]);assert.equal(q.get('plan_code'),'施-2');assert.equal(q.get('lang'),'en');e.requests.at(-1).resolve(fixture('S1-1','S2-1',{prompt:'EN CURRENT PLAN'}));await call;assert.equal(await e.call('wpkCopy'),true);assert.equal(e.copies[0],'EN CURRENT PLAN');});
test('detached old controls cannot change search or selection after root replacement',async()=>{const e=harness();await finish(e);const old=e.state().host,input=e.node('[data-wpk-search]'),task=e.node('[data-wpk-task]');e.changeRoot();input.value='old text';old.dispatch('input',input);old.dispatch('click',task);assert.equal(e.state().query,'');assert.equal(e.state().selected,'');assert.equal(e.requests.length,2);});
test('raw task state stays distinct from board column and actual owner/dependency are shown without guessing',async()=>{const e=harness(),p=fixture();p.task={...p.task,text:'待你验收',col:'等验收',who:'G真实',wait_on:'S1-2 S2-1'};await finish(e,p);const html=e.node('[data-wpk-package]').innerHTML;assert.match(html,/<p class="wpk-state">待你验收/);assert.match(html,/G真实/);assert.match(html,/S1-2 S2-1/);assert.equal(e.state().package.task.col,'等验收');});
test('actual-template hooks include virtual node after Code list, openItem dispatch and project-root reset',{skip:staged?'TEMP source only; root owns production insertion':false},()=>{assert.match(template,/path\s*===\s*WORKBENCH[^\n]*showWorkPackage\(/);assert.match(template,/path:CODELIST[\s\S]{0,220}path:WORKBENCH/);assert.match(template,/function render\(s\)[\s\S]{0,220}wpkProjectChanged\(/);});
