'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {fixture}=require('./test_pane_spirit.js');
function scanProtocolFixture(){
  const html=fs.readFileSync(path.join(__dirname,'../../模板.html'),'utf8'),begin=html.indexOf('let MYAREAS ='),end=html.indexOf('function sendFocus()',begin),states=[];
  const socket={readyState:1},c={S:{project:{root:'C:/临时/甲'}},ws:socket,online:true,window:{PaneSpirit:{scan:active=>states.push(active)}},setConn(){},api:async()=>({project:'C:/临时/甲',busy:[]})};
  vm.createContext(c);vm.runInContext(html.slice(begin,end),c);return{c,socket,states,run:s=>vm.runInContext(s,c)};
}
test('scan events use only the current live connection and exact project',()=>{const f=scanProtocolFixture();assert.equal(f.c.handleScanMessage({active:true,areas:['核心'],project:'C:/临时/乙'},f.socket),false);assert.equal(f.c.handleScanMessage({active:true,areas:['核心']},{}),false);assert.equal(f.states.length,0);assert.equal(f.c.handleScanMessage({active:true,areas:['核心'],project:'C:/临时/甲'},f.socket),true);assert.equal(f.run('SCANBUSY'),'核心');assert.deepEqual(f.states,[true]);f.c.handleScanMessage({active:false,areas:[],project:'C:/临时/甲'},f.socket);assert.equal(f.run('SCANBUSY'),'');assert.deepEqual(f.states,[true,false]);});
test('disconnect resets scanning and an old busy query cannot revive its flame',async()=>{const f=scanProtocolFixture();let resolve;f.c.api=()=>new Promise(r=>resolve=r);const work=f.c.syncScanState(f.socket);f.c.resetScanState();f.socket.readyState=3;resolve({project:'C:/临时/甲',busy:['核心']});await work;assert.deepEqual(f.states,[false]);});
test('a scan event supersedes an earlier read-only scan query',async()=>{const f=scanProtocolFixture();let resolve;f.c.api=()=>new Promise(r=>resolve=r);const work=f.c.syncScanState(f.socket);f.c.handleScanMessage({active:false,areas:[],project:'C:/临时/甲'},f.socket);resolve({project:'C:/临时/甲',busy:['核心']});await work;assert.deepEqual(f.states,[false]);assert.equal(f.run('SCANBUSY'),'');});
test('a project change rejects its pending scan response',async()=>{const f=scanProtocolFixture();let resolve;f.c.api=()=>new Promise(r=>resolve=r);const work=f.c.syncScanState(f.socket);f.c.S={project:{root:'C:/临时/乙'}};resolve({project:'C:/临时/甲',busy:['核心']});await work;assert.deepEqual(f.states,[]);});
test('initial scan query is GET only and reports the actual busy state',async()=>{const f=scanProtocolFixture(),calls=[];f.c.api=async(method,url)=>{calls.push([method,url]);return{project:'C:/临时/甲',busy:['笔记']}};await f.c.syncScanState(f.socket);assert.deepEqual(calls,[['GET','api/scan']]);assert.deepEqual(f.states,[true]);assert.equal(f.run('SCANBUSY'),'笔记');});
test('governance reader checks selection again after successful convergence',async()=>{const map=require('../../治理界面.js');let finish;const merge=new Promise(r=>finish=r),shown=[];const reader=map.createReader({context:()=>({root:'甲'}),isCurrent:()=>true,request:async()=>({text:'正文'}),complete:()=>merge,result:node=>shown.push(node.id),error(){throw Error('Unexpected error')}});const first=reader.select({id:'old',preview:{mode:'project',path:'治理/目标/S0.md'}});await new Promise(setImmediate);reader.invalidate();finish(true);await first;assert.deepEqual(shown,[]);});
test('governance reader does not converge an error into success',async()=>{const map=require('../../治理界面.js');let merged=0,errors=0;const reader=map.createReader({context:()=>({root:'甲'}),isCurrent:()=>true,request:async()=>{throw Error('真实错误')},complete:()=>{merged++},result(){throw Error('False success')},error:()=>errors++});await reader.select({id:'a',preview:{mode:'project',path:'治理/目标/S0.md'}});assert.equal(merged,0);assert.equal(errors,1);});
function loadingFixture(f,parent){
  const host=f.el('article','',parent||f.document.body),loading=f.el('span','ps-loading',host),label=f.el('span','ps-loading-text',loading),fires=f.el('span','ps-loading-fires',loading);label.textContent='正在读取';for(const color of ['jade','violet','gold'])f.el('svg','ps-loading-fire ps-loading-'+color,fires);return {host,loading,label,fires};
}
function animationClock(f,reduced=false){
  let next=1;const timers=new Map(),cleared=[],listeners=new Set(),media={matches:reduced,addEventListener(type,fn){if(type==='change')listeners.add(fn);},removeEventListener(type,fn){listeners.delete(fn);}};
  f.window.setTimeout=(fn,delay)=>{const id=next++;timers.set(id,{fn,delay});return id;};f.window.clearTimeout=id=>{cleared.push(id);timers.delete(id);};f.window.matchMedia=query=>{assert.equal(query,'(prefers-reduced-motion: reduce)');return media;};
  return {timers,cleared,listeners,media,run(){for(const [id,t]of [...timers]){timers.delete(id);t.fn();}},reduce(){media.matches=true;for(const fn of [...listeners])fn({matches:true});}};
}

test('loading renders exactly three actual SVG flames with a readable status and no controls or network',()=>{
  const f=fixture();try{const html=f.window.PaneSpirit.loading('正在读取');assert.equal((html.match(/<svg\b/g)||[]).length,3);assert.equal((html.match(/<path\b/g)||[]).length,3);assert.ok(html.includes('role="status"'));assert.ok(html.includes('aria-live="polite"'));assert.ok(html.includes('aria-atomic="true"'));assert.ok(html.includes('ps-loading-jade'));assert.ok(html.includes('ps-loading-violet'));assert.ok(html.includes('ps-loading-gold'));assert.ok(html.indexOf('ps-loading-text')<html.indexOf('ps-loading-fires'),'text comes before the three flames');assert.ok(html.indexOf('ps-loading-jade')<html.indexOf('ps-loading-violet'));assert.ok(html.indexOf('ps-loading-violet')<html.indexOf('ps-loading-gold'));assert.ok(html.includes('正在读取'));assert.ok(!/<(?:img|button|iframe|script)\b/.test(html));assert.equal(f.document.querySelectorAll('.ps-fire').length,0);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('loading escapes plain text, preserves English and does not treat a caption as markup',()=>{
  const f=fixture();try{const caption='<img src=x onerror="start()"> & \'quoted\'',html=f.window.PaneSpirit.loading(caption);assert.ok(html.includes('&lt;img src=x onerror=&quot;start()&quot;&gt; &amp; &#39;quoted&#39;'));assert.ok(!html.includes('<img'));assert.ok(f.window.PaneSpirit.loading('Reading').includes('>Reading</span>'));assert.ok(f.window.PaneSpirit.loading().includes('正在读取'));assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('repeated loading and scan calls reuse one stylesheet and do not create panes or employee windows',()=>{
  const f=fixture();try{const style=f.document.getElementById('pane-spirit-style');for(let i=0;i<8;i++){f.window.PaneSpirit.loading('Loading');f.window.PaneSpirit.scan(i%2===0);}assert.equal(f.document.getElementById('pane-spirit-style'),style);assert.equal(f.document.head.children.filter(x=>x.id==='pane-spirit-style').length,1);assert.equal(f.document.querySelectorAll('.ps-fire').length,0);assert.equal(f.document.querySelectorAll('.ps-collapse-button').length,0);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('ordinary DOM discovery never invents scan activity and non-booleans never replace real scan state',()=>{
  const f=fixture();try{const {p}=f.pane(),c=f.window.PaneSpirit.attach(p),api=f.window.PaneSpirit;assert.equal(api.scan(),false);assert.ok(!c.token.classList.contains('ps-scanning'));assert.equal(api.scan('true'),false);assert.equal(api.scan({active:true}),false);assert.equal(api.scan(true),true);assert.equal(api.scan(),true);assert.equal(api.scan(null),true);const input=f.el('input','',p);f.observers[0].deliver([{type:'childList',target:p,addedNodes:[input],removedNodes:[]}]);f.flush();assert.ok(c.token.classList.contains('ps-scanning'));assert.equal(api.scan(false),false);assert.equal(api.scan(),false);assert.ok(!c.token.classList.contains('ps-scanning'));assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('new panes inherit actual scan activity while removing one pane does not clear another pane state',()=>{
  const f=fixture();try{const api=f.window.PaneSpirit;api.scan(true);const {p}=f.pane(),c=api.attach(p),next=f.pane('wfe-reading','wfe-scene'),other=api.attach(next.p);assert.ok(c.token.classList.contains('ps-scanning'));assert.ok(other.token.classList.contains('ps-scanning'));c.collapse();other.collapse();api.dispose(p);assert.equal(c.destroyed,true);assert.ok(other.token.classList.contains('ps-scanning'));assert.equal(api.scan(),true);api.scan(false);assert.ok(!other.token.classList.contains('ps-scanning'));assert.equal(other.collapsed,true);assert.equal(other.token.hidden,false);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('own animation-state class changes do not start an observer feedback loop',()=>{
  const f=fixture();try{const {p}=f.pane(),c=f.window.PaneSpirit.attach(p);f.window.PaneSpirit.scan(true);f.observers[0].deliver([{type:'attributes',target:c.token,attributeName:'class'},{type:'attributes',target:c.image,attributeName:'style'}]);assert.equal(f.flush(),0);assert.equal(c.button.events.get('click').size,1);assert.equal(c.token.events.get('click').size,1);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('three flames use staggered transform animation and reduced motion leaves both loading and scan flames static',()=>{
  const f=fixture();try{const css=f.document.getElementById('pane-spirit-style').textContent;assert.ok(/\.ps-loading-jade\{[^}]*animation-delay:0s/.test(css));assert.ok(/\.ps-loading-violet\{[^}]*animation-delay:\.16s/.test(css));assert.ok(/\.ps-loading-gold\{[^}]*animation-delay:\.32s/.test(css));assert.ok(/\.ps-loading-fires\{[^}]*width:2\.05rem;[^}]*height:1\.2rem/.test(css));assert.ok(/\.ps-fire\.ps-scanning img\{[^}]*animation:ps-scan-flicker \.72s/.test(css));const reduced=css.match(/@media\(prefers-reduced-motion:reduce\)\{([^{}]*)\{animation:none;transform:none\}\}/);assert.ok(reduced);for(const selector of ['.ps-loading-fire','.ps-fire.ps-scanning img','.ps-completing .ps-loading-fire','.ps-completing .ps-loading-result','.ps-failing .ps-loading-fire','.ps-loading-failed .ps-loading-fire'])assert.ok(reduced[1].split(',').map(x=>x.trim()).includes(selector),'reduce stops '+selector);assert.ok(/\.ps-loading-failed \.ps-loading-fire\{animation:ps-loading-hop 1\.12s ease-in-out infinite/.test(css),'settled failure keeps independent hops');const keyframes=css.match(/@keyframes\s+[\w-]+\s*\{(?:[^{}]|\{[^{}]*\})*\}/g).join('');assert.ok(!/(?:left|right|top|bottom|width|height|padding|margin):/.test(keyframes));assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('the single restored-pane SVG keeps three thin local flames and its own reduced-motion rule',()=>{
  const svg=fs.readFileSync(path.resolve(__dirname,'../../外观/图标/精气神.svg'),'utf8');assert.equal((svg.match(/<svg\b/g)||[]).length,1);assert.equal((svg.match(/<path\b/g)||[]).length,3);assert.ok(svg.includes('stroke-width=".9"'));assert.ok(svg.includes('.spirit-tongue{animation:none}'));assert.ok(!/<(?:image|script|foreignObject)\b/.test(svg));assert.ok(!/(?:href|src)="https?:/.test(svg));
});
test('the plain-text loading API also works without a DOM or a network capability',()=>{
  const source=fs.readFileSync(path.resolve(__dirname,'../../小窗.js'),'utf8'),module={exports:{}};vm.runInNewContext(source,{module,exports:module.exports,console});const api=module.exports;assert.equal(typeof api.loading,'function');assert.equal((api.loading('Reading').match(/<svg\b/g)||[]).length,3);assert.equal(api.scan(true),true);assert.equal(api.scan(),true);api.dispose();assert.equal(api.scan(),false);
});
test('completion rejects an absent, detached or unrelated host without starting an animation',async()=>{
  const f=fixture();try{const clock=animationClock(f),api=f.window.PaneSpirit,empty=f.el('article','',f.document.body),old=loadingFixture(f);assert.equal(await api.complete(null),false);assert.equal(await api.complete(empty),false);old.host.remove();assert.equal(await api.complete(old.host),false);const broken=loadingFixture(f);broken.fires.remove();assert.equal(await api.complete(broken.host),false);assert.equal(clock.timers.size,0);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('only an explicit success completion merges the three flames and reuses one Promise and one result',async()=>{
  const f=fixture();try{const clock=animationClock(f),{host,loading,fires}=loadingFixture(f),api=f.window.PaneSpirit;assert.equal(clock.timers.size,0);assert.equal(loading.querySelector('.ps-loading-result'),null);api.scan();api.loading('Reading');assert.equal(clock.timers.size,0);const promise=api.complete(host),again=api.complete(host);assert.equal(promise,again);assert.ok(loading.classList.contains('ps-completing'));assert.equal(fires.children.filter(x=>x.tagName==='SVG').length,3);assert.equal(fires.children.filter(x=>x.tagName==='IMG').length,1);const image=loading.querySelector('.ps-loading-result');assert.equal(image.src,'icons/精气神.svg');let settled=false;promise.then(()=>settled=true);await Promise.resolve();assert.equal(settled,false);fires.children[0].dispatchEvent({type:'animationend',animationName:'ps-loading-hop',bubbles:true});assert.equal(loading.classList.contains('ps-loading-complete'),false);image.dispatchEvent({type:'animationend',animationName:'ps-loading-result',bubbles:true});assert.equal(await promise,true);assert.equal(loading.classList.contains('ps-completing'),false);assert.ok(loading.classList.contains('ps-loading-complete'));assert.equal(clock.timers.size,0);assert.equal(clock.listeners.size,0);assert.equal(api.complete(host),promise);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('a success-animation timeout settles once even when a browser omits animationend',async()=>{
  const f=fixture();try{const clock=animationClock(f),{host,loading}=loadingFixture(f),promise=f.window.PaneSpirit.complete(host);assert.equal(clock.timers.size,1);assert.equal([...clock.timers.values()][0].delay,320);clock.run();assert.equal(await promise,true);assert.ok(loading.classList.contains('ps-loading-complete'));assert.equal(clock.timers.size,0);assert.equal(clock.listeners.size,0);clock.run();assert.equal(loading.querySelectorAll('.ps-loading-result').length,1);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('a replaced loader cannot mark new content complete or mutate its replacement',async()=>{
  const f=fixture();try{const clock=animationClock(f),{host,loading}=loadingFixture(f),promise=f.window.PaneSpirit.complete(host);loading.remove();const fresh=f.el('span','ps-loading',host),caption=f.el('span','ps-loading-text',fresh);caption.textContent='新的请求';clock.run();assert.equal(await promise,false);assert.equal(fresh.classList.contains('ps-loading-complete'),false);assert.equal(fresh.querySelector('.ps-loading-result'),null);assert.equal(caption.textContent,'新的请求');assert.equal(loading.querySelector('.ps-loading-result'),null);assert.equal(clock.listeners.size,0);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('leaving the page makes a pending completion false without opening or restoring any pane',async()=>{
  const f=fixture();try{const clock=animationClock(f),{host,loading}=loadingFixture(f),promise=f.window.PaneSpirit.complete(host);host.remove();clock.run();assert.equal(await promise,false);assert.equal(loading.classList.contains('ps-loading-complete'),false);assert.equal(loading.querySelector('.ps-loading-result'),null);assert.equal(f.document.querySelectorAll('.ps-fire').length,0);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('reduced motion completes immediately without scheduling the 300ms animation',async()=>{
  const f=fixture();try{const clock=animationClock(f,true),{host,loading,label}=loadingFixture(f),promise=f.window.PaneSpirit.complete(host);assert.ok(loading.classList.contains('ps-loading-complete'));assert.equal(loading.classList.contains('ps-completing'),false);assert.equal(await promise,true);assert.equal(clock.timers.size,0);assert.equal(clock.listeners.size,0);assert.equal(label.textContent,'正在读取');assert.equal(loading.querySelectorAll('.ps-loading-result').length,1);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('switching reduced motion on during completion settles and removes timer and listeners',async()=>{
  const f=fixture();try{const clock=animationClock(f),{host,loading}=loadingFixture(f),promise=f.window.PaneSpirit.complete(host);assert.equal(clock.listeners.size,1);clock.reduce();assert.equal(await promise,true);assert.ok(loading.classList.contains('ps-loading-complete'));assert.equal(clock.timers.size,0);assert.equal(clock.listeners.size,0);assert.equal(loading.events.get('animationend').size,0);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('completion preserves a pane and terminal while its result uses the same local flame and bounded fallback',async()=>{
  const f=fixture();try{const clock=animationClock(f),{p,parent,frame,input}=f.pane(),c=f.window.PaneSpirit.attach(p),{host,loading}=loadingFixture(f,p),button=c.button,rect=parent.getBoundingClientRect(),promise=f.window.PaneSpirit.complete(host),image=loading.querySelector('.ps-loading-result');image.dispatchEvent({type:'error'});assert.equal(decodeURI(image.src),'pfiles/外观/图标/精气神.svg');const fallback=image.src;image.dispatchEvent({type:'error'});assert.equal(image.src,fallback);clock.run();assert.equal(await promise,true);assert.equal(c.button,button);assert.equal(frame.parentNode,p);assert.equal(frame.src,'http://127.0.0.1/real-existing-window');assert.equal(input.value,'人的未保存输入');assert.deepEqual(parent.getBoundingClientRect(),rect);assert.equal(c.collapsed,false);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('disposing a pane cancels its completion and does not complete the old host',async()=>{
  const f=fixture();try{const clock=animationClock(f),{p}=f.pane(),c=f.window.PaneSpirit.attach(p),{host,loading}=loadingFixture(f,p),promise=f.window.PaneSpirit.complete(host);f.window.PaneSpirit.dispose(p);assert.equal(await promise,false);assert.equal(c.destroyed,true);assert.equal(loading.classList.contains('ps-loading-complete'),false);assert.equal(clock.timers.size,0);assert.equal(clock.listeners.size,0);assert.equal(loading.querySelector('.ps-loading-result'),null);assert.equal(f.external.length,0);}finally{f.cleanup();}
});
test('failed data replaced with an error stays an error and receives no automatic success flame',async()=>{
  const f=fixture();try{const clock=animationClock(f),{host,loading}=loadingFixture(f);try{await Promise.reject(new Error('真实读取失败'));}catch(e){loading.remove();const error=f.el('p','read-error',host);error.setAttribute('role','alert');error.textContent=e.message;}f.window.PaneSpirit.scan(true);f.window.PaneSpirit.scan(false);clock.run();assert.equal(host.querySelector('.read-error').textContent,'真实读取失败');assert.equal(host.querySelector('.ps-loading-result'),null);assert.equal(clock.timers.size,0);assert.equal(f.external.length,0);}finally{f.cleanup();}
});

// Read the real template functions/CSS; TEMP overrides are only for root-owned insertion staging.
const connTemplate=fs.readFileSync(path.resolve(__dirname,'../../模板.html'),'utf8');
const connStaged=!!process.env.MH_CONNECTION_SPIRIT_SOURCE;
function connExtract(text,begin,end){const a=text.indexOf(begin),b=text.indexOf(end,a);assert.ok(a>=0&&b>a,'Missing production connection block: '+begin);return text.slice(a,b);}
const connSource=connExtract(connStaged?fs.readFileSync(process.env.MH_CONNECTION_SPIRIT_SOURCE,'utf8'):connTemplate,'/* ================= 顶部连接火苗 Connection spirit ================= */','/* ================= 顶部连接火苗 Connection spirit 结束 ================= */');
const connCss=connExtract(process.env.MH_CONNECTION_SPIRIT_CSS?fs.readFileSync(process.env.MH_CONNECTION_SPIRIT_CSS,'utf8'):connTemplate,'/* ================= 顶部连接火苗 Connection spirit CSS ================= */','/* ================= 顶部连接火苗 Connection spirit CSS 结束 ================= */');
function connectionFixture(){
  const f=fixture(),tail=f.el('span','tail',f.document.body);tail.id='conn';tail.dataset={};let html='',writes=0,modes=0,resets=0,saved=0;
  const originalSet=tail.setAttribute.bind(tail);tail.setAttribute=(key,value)=>{if(key==='data-conn-mode')modes++;originalSet(key,value);};
  Object.defineProperty(tail,'innerHTML',{get:()=>html,set:value=>{html=String(value);writes++;for(const child of [...tail.children])child.remove();const stack=[tail];for(const token of html.matchAll(/<\/?[A-Za-z][^>]*>/g)){const tag=token[0];if(tag.startsWith('</')){if(stack.length>1)stack.pop();continue;}const node=f.document.createElement(tag.match(/^<([\w]+)/)[1]);for(const a of tag.matchAll(/([\w-]+)="([^"]*)"/g)){if(a[1]==='class')node.className=a[2];else node.setAttribute(a[1],a[2]);if(a[1]==='id')node.id=a[2];}stack.at(-1).appendChild(node);if(!/\/>$/.test(tag))stack.push(node);}}});
  const c={S:{materials:{total:12}},online:false,SCANBUSY:'',noteDirty:false,getLang:()=>f.window.getLang(),$:selector=>selector==='#conn'?tail:null,resetScanState(){resets++;c.SCANBUSY='';},saveNote(){saved++;},setTimeout(){throw Error('No connection timer');},setInterval(){throw Error('No connection loop');},api(){throw Error('No connection API');},fetch(){throw Error('No connection fetch');}};
  vm.createContext(c);vm.runInContext(connSource,c);return{f,c,tail,set:mode=>c.setConn(mode),run:script=>vm.runInContext(script,c),counts:()=>({writes,modes,resets,saved}),cleanup:()=>f.cleanup()};
}
function cssBlocks(text,reduced=false){const out=[];let at=0;while(at<text.length){const open=text.indexOf('{',at);if(open<0)break;const head=text.slice(at,open).replace(/\/\*[\s\S]*?\*\//g,'').trim();let i=open+1,depth=1;while(i<text.length&&depth){if(text[i]==='{')depth++;if(text[i]==='}')depth--;i++;}const body=text.slice(open+1,i-1);if(head.startsWith('@media'))out.push(...cssBlocks(body,true));else if(!head.startsWith('@'))out.push({selectors:head.split(',').map(x=>x.trim()),body,reduced});at=i;}return out;}
const connRules=cssBlocks(connCss);
function connSelector(node,selector){const parts=selector.split(/\s+/);let current=node;for(let i=parts.length-1;i>=0;i--){const match=n=>{const token=parts[i],attr=token.match(/\[([^=]+)="([^\"]+)"\]/),base=token.replace(/\[[^\]]*\]/g,'').replace(/:empty$/,'');return(base.startsWith('#')?n.id===base.slice(1):n.classList.contains(base.slice(1)))&&(!attr||n.getAttribute(attr[1])===attr[2]);};if(i===parts.length-1){if(!match(current))return false;current=current.parentNode;}else{while(current&&!match(current))current=current.parentNode;if(!current)return false;current=current.parentNode;}}return true;}
function connComputed(node,reduced=false){const props={};for(const rule of connRules){if(rule.reduced&&!reduced||!rule.selectors.some(s=>connSelector(node,s)))continue;for(const declaration of rule.body.split(';')){const colon=declaration.indexOf(':');if(colon<0)continue;props[declaration.slice(0,colon).trim()]=declaration.slice(colon+1).trim();}}return props;}
test('connection markup has caption before exactly three local thin jade violet gold SVGs',()=>{const x=connectionFixture();try{x.set('off');const fire=x.tail.querySelector('.conn-fires'),svg=fire.children.filter(n=>n.tagName==='SVG');assert.equal(svg.length,3);assert.ok(svg[0].classList.contains('conn-fire-jade'));assert.ok(svg[1].classList.contains('conn-fire-violet'));assert.ok(svg[2].classList.contains('conn-fire-gold'));assert.equal(x.tail.children[0].className,'conn-caption');assert.equal(fire.getAttribute('aria-hidden'),'true');assert.equal(x.tail.getAttribute('role'),'status');assert.equal(x.tail.getAttribute('aria-live'),'polite');assert.ok(!/<(?:img|script|iframe|a|button)\b/.test(x.tail.innerHTML));assert.ok(!/(?:href|src)=/.test(x.tail.innerHTML));for(const path of svg.flatMap(n=>n.querySelectorAll('*')).filter(n=>n.tagName==='PATH'))assert.equal(path.getAttribute('stroke-width'),'.9');assert.equal(x.f.external.length,0);}finally{x.cleanup();}});
test('same connected refresh preserves every flame and animation mode while updating real caption and scan text',()=>{const x=connectionFixture();try{x.set('on');const fire=x.tail.querySelector('.conn-fires'),svgs=[...fire.children],caption=x.tail.querySelector('.conn-caption'),before=x.counts();for(let i=0;i<8;i++){x.c.S.materials.total=20+i;x.c.SCANBUSY='扫描甲'+i;x.set('on');}assert.equal(x.tail.querySelector('.conn-fires'),fire);assert.deepEqual(fire.children,svgs);assert.equal(x.tail.querySelector('.conn-caption'),caption);assert.equal(x.counts().writes,before.writes);assert.equal(x.counts().modes,before.modes);assert.equal(caption.textContent,'已连后端 · 资料/ 27 个文件');assert.equal(x.tail.querySelector('.conn-scan').textContent,' · 扫着 扫描甲7…');assert.equal(x.c.online,true);assert.equal(x.counts().resets,0);}finally{x.cleanup();}});
test('only real setConn modes control connection state; lost/off retain the same SVGs and reset scan truthfully',()=>{const x=connectionFixture();try{x.set('on');const fires=x.tail.querySelector('.conn-fires');x.c.SCANBUSY='旧扫描';x.set('lost');assert.equal(x.c.online,false);assert.equal(x.tail.dataset.connMode,'lost');assert.equal(x.tail.querySelector('.conn-caption').textContent,'后端断了 · 重连中…');assert.equal(x.tail.querySelector('.conn-scan').textContent,'');x.set('file');assert.equal(x.tail.dataset.connMode,'off');assert.equal(x.tail.querySelector('.conn-caption').textContent,'没连后端 · 双击「启动.bat」');assert.equal(x.tail.querySelector('.conn-fires'),fires);assert.equal(x.counts().writes,1);assert.equal(x.counts().resets,2);assert.equal(x.counts().saved,0);}finally{x.cleanup();}});
test('scan labels remain escaped plain text and unknown file counts do not invent a number',()=>{const x=connectionFixture();try{x.c.S={};x.c.SCANBUSY='<img src=x onerror="run()">';x.set('on');assert.equal(x.tail.querySelector('.conn-caption').textContent,'已连后端 · 文件数未知');assert.equal(x.tail.querySelector('.conn-scan').textContent,' · 扫着 <img src=x onerror="run()">…');assert.ok(!x.tail.innerHTML.includes('<img'));assert.equal(x.f.external.length,0);}finally{x.cleanup();}});
test('connection flame keeps the existing deferred-note save behavior and does not run anything else',()=>{const x=connectionFixture();try{x.c.noteDirty=true;x.set('lost');assert.equal(x.counts().saved,0);x.set('on');assert.equal(x.counts().saved,1);assert.equal(x.f.external.length,0);assert.doesNotMatch(connSource,/setInterval\(|setTimeout\(|fetch\(|api\(/);}finally{x.cleanup();}});
test('connection English captions update without rebuilding decorative flames',()=>{const x=connectionFixture();try{x.set('on');const fires=x.tail.querySelector('.conn-fires');x.f.setLanguage('en');x.c.SCANBUSY='core';x.set('on');assert.equal(x.tail.querySelector('.conn-caption').textContent,'Backend connected · materials/ 12 files');assert.equal(x.tail.querySelector('.conn-scan').textContent,' · Scanning core…');x.set('lost');assert.equal(x.tail.querySelector('.conn-caption').textContent,'Backend disconnected · Reconnecting…');assert.equal(x.tail.querySelector('.conn-fires'),fires);assert.equal(x.counts().writes,1);}finally{x.cleanup();}});
test('real CSS binds fixed-size geometry and looping merge to the actual connected DOM selectors',()=>{const x=connectionFixture();try{x.set('on');const container=x.tail.querySelector('.conn-fires'),jade=x.tail.querySelector('.conn-fire-jade'),middle=x.tail.querySelector('.conn-fire-violet'),mix=x.tail.querySelector('.conn-spirit-shape'),cs=connComputed(container);assert.equal(cs.width,'2rem');assert.equal(cs.height,'1.15rem');assert.equal(cs.flex,'0 0 2rem');assert.equal(connComputed(jade).animation,'conn-linked-merge 5.4s ease-in-out infinite');assert.equal(connComputed(middle).animation,'conn-linked-center 5.4s ease-in-out infinite');assert.equal(connComputed(mix).animation,'conn-linked-spirit 5.4s ease-in-out infinite');assert.match(connCss,/@keyframes conn-linked-merge\{[^}]*opacity:1\}[^}]*translateX\(0\)[^}]*opacity:0/);assert.match(connCss,/@keyframes conn-linked-spirit\{[^}]*opacity:0\}[^}]*opacity:1/);}finally{x.cleanup();}});
test('off and lost actual CSS bindings retain one baseline with distinct independent hop timing',()=>{const x=connectionFixture();try{x.set('off');const a=x.tail.querySelector('.conn-fire-jade'),b=x.tail.querySelector('.conn-fire-violet'),c=x.tail.querySelector('.conn-fire-gold');for(const node of [a,b,c])assert.equal(connComputed(node).animation,'conn-wait-hop 1.12s ease-in-out infinite');x.set('lost');assert.equal(connComputed(a).bottom,'0');assert.equal(connComputed(b).bottom,'0');assert.equal(connComputed(c).bottom,'0');assert.equal(connComputed(a).animation,'conn-lost-hop 1.19s ease-in-out infinite');assert.equal(connComputed(b)['animation-duration'],'1.47s');assert.equal(connComputed(c)['animation-duration'],'1.31s');assert.equal(connComputed(b)['animation-delay'],'.21s');assert.equal(connComputed(c)['animation-delay'],'.43s');const keyframes=connCss.match(/@keyframes\s+[\w-]+\s*\{(?:[^{}]|\{[^{}]*\})*\}/g).join('');assert.doesNotMatch(keyframes,/(?:left|right|top|bottom|width|height|padding|margin):/);}finally{x.cleanup();}});
test('reduced motion actual CSS shows one static merged connected spirit and three static lost flames',()=>{const x=connectionFixture();try{x.set('on');const a=x.tail.querySelector('.conn-fire-jade'),b=x.tail.querySelector('.conn-fire-violet'),c=x.tail.querySelector('.conn-fire-gold'),mix=x.tail.querySelector('.conn-spirit-shape');for(const node of [a,b,c,mix])assert.equal(connComputed(node,true).animation,'none!important');assert.equal(connComputed(a,true).opacity,'0');assert.equal(connComputed(c,true).opacity,'0');assert.equal(connComputed(b,true).transform,'translateX(0)');assert.equal(connComputed(mix,true).opacity,'1');x.set('lost');for(const node of [a,b,c]){const cs=connComputed(node,true);assert.equal(cs.animation,'none!important');assert.equal(cs.opacity,'1');assert.equal(cs.transform,'translateX(var(--conn-x))');}assert.equal(connComputed(mix,true).opacity,'0');assert.equal(x.c.online,false);}finally{x.cleanup();}});
test('actual initial connection HTML exposes stable text-first offline flames without a legacy dot',{skip:connStaged?'TEMP source only; root owns initial HTML insertion':false},()=>{const initial=connTemplate.match(/<span[^>]*id="conn"[^>]*>[\s\S]*?<\/span>\s*<\/div>/);assert.ok(initial,'Initial connection tail is in the template');assert.ok(initial[0].includes('conn-caption'));assert.ok(initial[0].includes('conn-fires'));assert.ok(initial[0].indexOf('conn-caption')<initial[0].indexOf('conn-fires'));assert.ok(!/class="dot/.test(initial[0]));});
